import type pg from 'pg';
import { ApiError } from '../shared/errors.js';

export type MatchStatus='accepting'|'ready'|'connecting'|'in_progress'|'completed'|'cancelled';
export const MATCH_TRANSITIONS:Readonly<Record<MatchStatus,readonly MatchStatus[]>>={accepting:['ready','cancelled'],ready:['connecting','cancelled'],connecting:['in_progress','cancelled'],in_progress:['completed','cancelled'],completed:[],cancelled:[]};
export type Completion={winner:'radiant'|'dire';radiantScore:number;direScore:number;durationSeconds:number;reason:string};
type Actor={type:'player'|'admin'|'system';id:string;ip?:string};
type Emit=(event:string,matchId:string,payload?:unknown)=>void;

export function assertTransition(from:MatchStatus,to:MatchStatus){if(!MATCH_TRANSITIONS[from].includes(to))throw new ApiError(409,'INVALID_MATCH_TRANSITION',`Cannot transition match from ${from} to ${to}`)}
export function calculateTeamElo(radiant:number[],dire:number[],winner:'radiant'|'dire',k=32){
  const avg=(v:number[])=>v.reduce((a,b)=>a+b,0)/v.length;
  const expected=1/(1+10**((avg(dire)-avg(radiant))/400));
  const raw=k*((winner==='radiant'?1:0)-expected);
  const radiantDelta=Math.max(-32,Math.min(32,Math.round(raw)));
  return {radiantDelta,direDelta:-radiantDelta,expectedRadiant:expected};
}
export class MatchLifecycleService{
  constructor(private pool:pg.Pool,private emit:Emit=()=>{}){}
  private async transaction<T>(fn:(client:pg.PoolClient)=>Promise<T>){const c=await this.pool.connect();try{await c.query('begin');const result=await fn(c);await c.query('commit');return result}catch(e){await c.query('rollback');throw e}finally{c.release()}}
  private async locked(c:pg.PoolClient,id:string){const {rows}=await c.query('select * from matches where id=$1 for update',[id]);if(!rows[0])throw new ApiError(404,'MATCH_NOT_FOUND','Match not found');return rows[0]}
  private async audit(c:pg.PoolClient,actor:Actor,id:string,action:string,oldState:string,newState:string,reason:string){await c.query(`insert into audit_logs(actor_type,actor_id,action,entity_type,entity_id,old_value,new_value,ip_address) values($1,$2,$3,'match',$4,$5,$6,$7)`,[actor.type,actor.id,action,id,{status:oldState,reason},{status:newState,reason},actor.ip??null])}
  private async transition(c:pg.PoolClient,m:any,to:MatchStatus,actor:Actor,reason:string){assertTransition(m.status,to);const stamp:{[k:string]:Date}={};const field:{[k:string]:string}={ready:'ready_at',connecting:'connecting_at',in_progress:'in_progress_at',completed:'completed_at',cancelled:'cancelled_at'};stamp[field[to]!]=new Date();const sets=Object.keys(stamp).map((k,i)=>`${k}=$${i+4}`);const values=Object.values(stamp);const result=await c.query(`update matches set status=$1,version=version+1,updated_at=now(),${sets.join(',')} where id=$2 and version=$3 returning *`,[to,m.id,m.version,...values]);if(!result.rows[0])throw new ApiError(409,'MATCH_VERSION_CONFLICT','Match was updated concurrently');await this.audit(c,actor,m.id,`match.${to}`,m.status,to,reason);return result.rows[0]}
  async accept(id:string,playerId:string){const events:string[]=[];const result=await this.transaction(async c=>{const m=await this.locked(c,id);const mp=(await c.query('select * from match_players where match_id=$1 and player_id=$2 for update',[id,playerId])).rows[0];if(!mp)throw new ApiError(403,'NOT_MATCH_PARTICIPANT','Not a match participant');if(mp.accept_status==='accepted')return {...await this.count(c,id,m.accept_deadline),idempotent:true};if(m.status!=='accepting')throw new ApiError(409,'INVALID_MATCH_TRANSITION','Match is not accepting');if(new Date(m.accept_deadline)<=new Date())throw new ApiError(409,'ACCEPT_TIMEOUT','Accept deadline expired');if(mp.accept_status!=='pending')throw new ApiError(409,'ACCEPT_STATUS_FINAL','Acceptance is already final');await c.query(`update match_players set accept_status='accepted',accepted_at=now() where match_id=$1 and player_id=$2`,[id,playerId]);events.push('match:acceptance_updated');const count=await this.count(c,id,m.accept_deadline);if(count.accepted===count.required){await this.transition(c,m,'ready',{type:'player',id:playerId},'All required players accepted');events.push('match:ready')}return count});for(const e of events)this.emit(e,id,result);return result}
  async decline(id:string,playerId:string,reason='Player declined'){const result=await this.transaction(async c=>{const m=await this.locked(c,id);const mp=(await c.query('select * from match_players where match_id=$1 and player_id=$2 for update',[id,playerId])).rows[0];if(!mp)throw new ApiError(403,'NOT_MATCH_PARTICIPANT','Not a match participant');if(mp.accept_status==='declined'&&m.status==='cancelled')return {idempotent:true};if(m.status!=='accepting'||mp.accept_status!=='pending')throw new ApiError(409,'INVALID_MATCH_TRANSITION','Match cannot be declined');await c.query(`update match_players set accept_status='declined' where match_id=$1 and player_id=$2`,[id,playerId]);await this.applyTrust(c,id,playerId,'match_decline',-2);await c.query('update matches set cancellation_reason=$2 where id=$1',[id,reason]);await this.transition(c,m,'cancelled',{type:'player',id:playerId},reason);await this.requeueInnocent(c,id);return {idempotent:false}});this.emit('trust:updated',id);this.emit('match:cancelled',id,result);return result}
  async beginConnecting(id:string,actor:Actor={type:'system',id:'worker'}){const result=await this.transaction(async c=>{const m=await this.locked(c,id);if(m.status==='connecting')return {idempotent:true};const next=await this.transition(c,m,'connecting',actor,'TRUST lobby readiness started');await c.query(`update match_players mp set connection_status=case when p.is_bot then 'connected' else 'connecting' end,connected_at=case when p.is_bot then now() else null end from players p where mp.match_id=$1 and p.id=mp.player_id`,[id]);return next});this.emit('match:connecting',id,result);return result}
  async connectionReady(id:string,playerId:string){let started=false;const result=await this.transaction(async c=>{let m=await this.locked(c,id);if(!['connecting','in_progress'].includes(m.status))throw new ApiError(409,'INVALID_MATCH_TRANSITION','Match is not connecting');const mp=(await c.query('select connection_status from match_players where match_id=$1 and player_id=$2',[id,playerId])).rows[0];if(!mp)throw new ApiError(403,'NOT_MATCH_PARTICIPANT','Not a match participant');if(mp.connection_status!=='connected')await c.query(`update match_players set connection_status='connected',connected_at=now(),connection_failure_reason=null where match_id=$1 and player_id=$2`,[id,playerId]);if(m.status==='connecting'){const pending=Number((await c.query(`select count(*) from match_players mp join players p on p.id=mp.player_id where mp.match_id=$1 and not p.is_bot and mp.connection_status<>'connected'`,[id])).rows[0].count);if(!pending){m=await this.transition(c,m,'in_progress',{type:'player',id:playerId},'All required players TRUST lobby ready');started=true}}return {match:m,idempotent:mp.connection_status==='connected'}});this.emit('match:connection_updated',id,result);if(started)this.emit('match:started',id,result);return result}
  async adminStart(id:string,ip?:string){const result=await this.transaction(async c=>{let m=await this.locked(c,id);if(m.status==='in_progress')return {match:m,idempotent:true};if(m.status==='ready')m=await this.transition(c,m,'connecting',{type:'admin',id:'bootstrap',ip},'Administrator started TRUST lobby readiness');if(m.status!=='connecting')throw new ApiError(409,'INVALID_MATCH_TRANSITION','Match cannot be started');m=await this.transition(c,m,'in_progress',{type:'admin',id:'bootstrap',ip},'Administrator confirmed start');return {match:m,idempotent:false}});this.emit('match:started',id,result);return result}
  async adminCancel(id:string,reason:string,ip?:string){if(!reason.trim())throw new ApiError(400,'CANCELLATION_REASON_REQUIRED','Cancellation reason is required');const result=await this.transaction(async c=>{const m=await this.locked(c,id);if(m.status==='cancelled'){if(m.cancellation_reason===reason)return {match:m,idempotent:true};throw new ApiError(409,'INVALID_MATCH_TRANSITION','Match is already cancelled')}if(m.status==='completed')throw new ApiError(409,'INVALID_MATCH_TRANSITION','Completed match cannot be cancelled');await c.query('update matches set cancellation_reason=$2 where id=$1',[id,reason]);const next=await this.transition(c,m,'cancelled',{type:'admin',id:'bootstrap',ip},reason);await this.requeueInnocent(c,id);return {match:next,idempotent:false}});this.emit('match:cancelled',id,result);return result}
  async complete(id:string,input:Completion,ip?:string){validateCompletion(input);const ratingUpdates:any[]=[];const result=await this.transaction(async c=>{const m=await this.locked(c,id);if(m.status==='completed'){const same=m.winner===input.winner&&m.radiant_score===input.radiantScore&&m.dire_score===input.direScore&&m.duration_seconds===input.durationSeconds&&m.completion_reason===input.reason;if(same)return {match:m,idempotent:true};throw new ApiError(409,'MATCH_RESULT_CONFLICT','Match already has a different result')}if(m.status!=='in_progress')throw new ApiError(409,'INVALID_MATCH_TRANSITION','Only an in-progress match can be completed');const roster=(await c.query(`select mp.*,p.rating,p.trust_score,p.is_bot from match_players mp join players p on p.id=mp.player_id where mp.match_id=$1 order by mp.player_id for update of p`,[id])).rows;const real=roster.filter(p=>!p.is_bot);const radiant=real.filter(p=>p.team==='radiant'),dire=real.filter(p=>p.team==='dire');const elo=calculateTeamElo(radiant.map(p=>p.rating_before),dire.map(p=>p.rating_before),input.winner);for(const p of real){const delta=p.team==='radiant'?elo.radiantDelta:elo.direDelta;const after=p.rating+delta;const reason='match_completion';await c.query(`insert into rating_events(player_id,match_id,reason,delta,value_before,value_after) values($1,$2,$3,$4,$5,$6) on conflict(match_id,player_id,reason) do nothing`,[p.player_id,id,reason,delta,p.rating,after]);await c.query(`update players set rating=$2,updated_at=now() where id=$1`,[p.player_id,after]);await c.query(`update match_players set rating_after=$3 where match_id=$1 and player_id=$2`,[id,p.player_id,after]);await this.applyTrust(c,id,p.player_id,'successful_match',1);ratingUpdates.push({playerId:p.player_id,ratingBefore:p.rating,ratingAfter:after,delta})}await c.query(`update matches set winner=$2,radiant_score=$3,dire_score=$4,duration_seconds=$5,completion_reason=$6,completed_by='admin' where id=$1`,[id,input.winner,input.radiantScore,input.direScore,input.durationSeconds,input.reason]);const next=await this.transition(c,m,'completed',{type:'admin',id:'bootstrap',ip},input.reason);return {match:{...next,winner:input.winner,radiant_score:input.radiantScore,dire_score:input.direScore,duration_seconds:input.durationSeconds,completion_reason:input.reason},idempotent:false,ratingUpdates}});this.emit('match:completed',id,result);for(const update of ratingUpdates)this.emit('rating:updated',id,update);this.emit('trust:updated',id);return result}
  async processTimeouts(now=new Date()){const ids=(await this.pool.query(`select id from matches where status='accepting' and accept_deadline <= $1 order by accept_deadline`,[now])).rows.map(r=>r.id);const results=[];for(const id of ids){try{results.push(await this.timeout(id,now))}catch{/* A broken match must not stop later timeout work. */}}return results}
  private async timeout(id:string,now:Date){const result=await this.transaction(async c=>{const m=await this.locked(c,id);if(m.status!=='accepting'||new Date(m.accept_deadline)>now)return {idempotent:true};const pending=(await c.query(`select mp.player_id,p.is_bot from match_players mp join players p on p.id=mp.player_id where mp.match_id=$1 and mp.accept_status='pending'`,[id])).rows;await c.query(`update match_players set accept_status='timed_out' where match_id=$1 and accept_status='pending'`,[id]);for(const p of pending)if(!p.is_bot)await this.applyTrust(c,id,p.player_id,'accept_timeout',-3);await c.query(`update matches set cancellation_reason='Accept deadline expired' where id=$1`,[id]);await this.transition(c,m,'cancelled',{type:'system',id:'accept-timeout-worker'},'Accept deadline expired');await this.requeueInnocent(c,id);return {idempotent:false}});if(!result.idempotent)this.emit('match:cancelled',id,result);return result}
  private async count(c:pg.PoolClient,id:string,deadline:Date){const row=(await c.query(`select count(*) filter(where accept_status='accepted')::int accepted,count(*)::int required from match_players where match_id=$1`,[id])).rows[0];return {...row,acceptDeadline:deadline}}
  private async applyTrust(c:pg.PoolClient,matchId:string,playerId:string,reason:string,delta:number){const p=(await c.query('select trust_score from players where id=$1 for update',[playerId])).rows[0];const after=Math.max(0,Math.min(100,p.trust_score+delta));const inserted=await c.query(`insert into trust_events(player_id,match_id,reason,delta,value_before,value_after) values($1,$2,$3,$4,$5,$6) on conflict(match_id,player_id,reason) do nothing returning id`,[playerId,matchId,reason,after-p.trust_score,p.trust_score,after]);if(inserted.rowCount){await c.query('update players set trust_score=$2,updated_at=now() where id=$1',[playerId,after]);await c.query('update match_players set trust_score_after=$3 where match_id=$1 and player_id=$2',[matchId,playerId,after])}}
  private async requeueInnocent(c:pg.PoolClient,matchId:string){await c.query(`insert into queue_entries(player_id,regions,primary_role,roles,rating_snapshot,trust_score_snapshot,status) select p.id,p.regions,mp.role,jsonb_build_array(mp.role),p.rating,p.trust_score,'waiting' from match_players mp join players p on p.id=mp.player_id where mp.match_id=$1 and mp.accept_status='accepted' and not p.is_bot and p.status='active' and not exists(select 1 from sanctions s where s.player_id=p.id and s.revoked_at is null and(s.expires_at is null or s.expires_at>now())) and not exists(select 1 from queue_entries q where q.player_id=p.id and q.status='waiting') and not exists(select 1 from match_players other join matches m on m.id=other.match_id where other.player_id=p.id and other.match_id<>$1 and m.status in('accepting','ready','connecting','in_progress')) on conflict do nothing`,[matchId])}
}
export function validateCompletion(v:Completion){if(!['radiant','dire'].includes(v.winner)||![v.radiantScore,v.direScore].every(n=>Number.isInteger(n)&&n>=0)||!Number.isInteger(v.durationSeconds)||v.durationSeconds<60||v.durationSeconds>21600||!v.reason?.trim())throw new ApiError(400,'INVALID_MATCH_RESULT','Winner, non-negative kill score, duration (60-21600), and reason are required')}
