import { sql } from 'drizzle-orm';
import { boolean, check, index, integer, jsonb, pgTable, primaryKey, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

const createdAt = () => timestamp('created_at', { withTimezone: true }).defaultNow().notNull();
export type LocalizedText = { en: string; ru?: string };

export const players = pgTable('players', {
  id: uuid('id').primaryKey().defaultRandom(),
  steamId: text('steam_id').unique(),
  displayName: text('display_name').notNull(), avatarUrl: text('avatar_url'), profileUrl: text('profile_url'),
  profileVisibility: integer('profile_visibility'), status: text('status').notNull().default('active'),
  rating: integer('rating').notNull().default(1000), trustScore: integer('trust_score').notNull().default(100),
  regions: jsonb('regions').$type<string[]>().notNull().default(['EU West']), preferredRole: text('preferred_role'),
  isBot: boolean('is_bot').notNull().default(false), createdAt: createdAt(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(), lastSeenAt: timestamp('last_seen_at', { withTimezone: true }),
}, (t) => ({ steam: uniqueIndex('players_steam_id_idx').on(t.steamId), status: index('players_status_idx').on(t.status), regions: index('players_regions_gin_idx').using('gin', t.regions), bot: index('players_is_bot_idx').on(t.isBot) }));

export const sessions = pgTable('sessions', {
  id: uuid('id').primaryKey().defaultRandom(), playerId: uuid('player_id').references(() => players.id, { onDelete: 'cascade' }).notNull(),
  tokenHash: text('token_hash').notNull(), createdAt: createdAt(), expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).defaultNow().notNull(), revokedAt: timestamp('revoked_at', { withTimezone: true }),
  ipAddress: text('ip_address'), userAgent: text('user_agent'),
}, (t) => ({ token: uniqueIndex('sessions_token_hash_idx').on(t.tokenHash), active: index('sessions_player_active_idx').on(t.playerId, t.expiresAt).where(sql`revoked_at is null`) }));

export const steamAuthStates = pgTable('steam_auth_states', {
  id: uuid('id').primaryKey().defaultRandom(), stateHash: text('state_hash').notNull(), createdAt: createdAt(), expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(), usedAt: timestamp('used_at', { withTimezone: true }),
}, (t) => ({ state: uniqueIndex('steam_auth_states_hash_idx').on(t.stateHash), expiry: index('steam_auth_states_expiry_idx').on(t.expiresAt) }));

export const playerRoles = pgTable('player_roles', { playerId: uuid('player_id').references(() => players.id, { onDelete: 'cascade' }).notNull(), role: text('role').notNull(), priority: integer('priority').notNull().default(1) }, (t) => ({ pk: primaryKey({ columns: [t.playerId, t.role] }) }));
export const queueEntries = pgTable('queue_entries', {
  id: uuid('id').primaryKey().defaultRandom(), playerId: uuid('player_id').references(() => players.id, { onDelete: 'cascade' }).notNull(),
  regions: jsonb('regions').$type<string[]>().notNull(), primaryRole: text('primary_role').notNull(), ratingSnapshot: integer('rating_snapshot').notNull(), trustScoreSnapshot: integer('trust_score_snapshot').notNull(),
  status: text('status').notNull().default('waiting'), joinedAt: timestamp('joined_at', { withTimezone: true }).defaultNow().notNull(), matchedAt: timestamp('matched_at', { withTimezone: true }), cancelledAt: timestamp('cancelled_at', { withTimezone: true }), version: integer('version').notNull().default(1),
}, (t) => ({ active: uniqueIndex('queue_one_active_per_player').on(t.playerId).where(sql`status = 'waiting'`), waiting: index('queue_waiting_idx').on(t.status, t.joinedAt), regions: index('queue_regions_gin_idx').using('gin', t.regions) }));

export const matches = pgTable('matches', { id: uuid('id').primaryKey().defaultRandom(), roomCode: text('room_code').notNull().unique(), region: text('region').notNull(), status: text('status').notNull().default('accepting'), acceptDeadline: timestamp('accept_deadline', { withTimezone: true }).notNull(), readyAt: timestamp('ready_at', { withTimezone: true }), connectingAt: timestamp('connecting_at', { withTimezone: true }), inProgressAt: timestamp('in_progress_at', { withTimezone: true }), startedAt: timestamp('started_at', { withTimezone: true }), completedAt: timestamp('completed_at', { withTimezone: true }), cancelledAt: timestamp('cancelled_at', { withTimezone: true }), winner: text('winner'), radiantScore: integer('radiant_score').notNull().default(0), direScore: integer('dire_score').notNull().default(0), durationSeconds: integer('duration_seconds'), completionReason: text('completion_reason'), completedBy: text('completed_by'), cancellationReason: text('cancellation_reason'), version: integer('version').notNull().default(1), createdAt: createdAt(), updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull() }, (t) => ({ status: index('matches_status_idx').on(t.status), statusDeadline: index('matches_status_deadline_idx').on(t.status,t.acceptDeadline), region: index('matches_region_idx').on(t.region), statusCheck: check('matches_status_check', sql`${t.status} in ('accepting','ready','connecting','in_progress','completed','cancelled')`), winnerCheck: check('matches_winner_check', sql`${t.winner} is null or ${t.winner} in ('radiant','dire')`), scoreCheck: check('matches_score_check', sql`${t.radiantScore} >= 0 and ${t.direScore} >= 0`), versionCheck: check('matches_version_check', sql`${t.version} > 0`) }));
export const matchPlayers = pgTable('match_players', { matchId: uuid('match_id').references(() => matches.id, { onDelete: 'cascade' }).notNull(), playerId: uuid('player_id').references(() => players.id, { onDelete: 'cascade' }).notNull(), team: text('team').notNull(), role: text('role').notNull(), acceptStatus: text('accept_status').notNull().default('pending'), acceptedAt: timestamp('accepted_at', { withTimezone: true }), connectionStatus: text('connection_status').notNull().default('pending'), connectedAt: timestamp('connected_at', { withTimezone: true }), connectionFailureReason: text('connection_failure_reason'), ratingBefore: integer('rating_before').notNull(), ratingAfter: integer('rating_after'), trustScoreBefore: integer('trust_score_before').notNull(), trustScoreAfter: integer('trust_score_after'), joinedAt: timestamp('joined_at', { withTimezone: true }).defaultNow().notNull() }, (t) => ({ pk: primaryKey({ columns: [t.matchId, t.playerId] }), player: index('match_players_player_idx').on(t.playerId), matchAccept: index('match_players_match_accept_idx').on(t.matchId,t.acceptStatus), matchConnection: index('match_players_match_connection_idx').on(t.matchId,t.connectionStatus), teamCheck: check('match_players_team_check',sql`${t.team} in ('radiant','dire')`), acceptCheck: check('match_players_accept_check',sql`${t.acceptStatus} in ('pending','accepted','declined','timed_out')`), connectionCheck: check('match_players_connection_check',sql`${t.connectionStatus} in ('pending','connecting','connected','failed')`) }));
export const ratingEvents = pgTable('rating_events', { id: uuid('id').primaryKey().defaultRandom(), playerId: uuid('player_id').references(() => players.id).notNull(), matchId: uuid('match_id').references(() => matches.id), reason: text('reason').notNull(), delta: integer('delta').notNull(), valueBefore: integer('value_before').notNull(), valueAfter: integer('value_after').notNull(), createdAt: createdAt() },t=>({idempotency:uniqueIndex('rating_events_match_player_reason_uidx').on(t.matchId,t.playerId,t.reason)}));
export const trustEvents = pgTable('trust_events', { id: uuid('id').primaryKey().defaultRandom(), playerId: uuid('player_id').references(() => players.id).notNull(), matchId: uuid('match_id').references(() => matches.id), reason: text('reason').notNull(), delta: integer('delta').notNull(), valueBefore: integer('value_before').notNull(), valueAfter: integer('value_after').notNull(), createdAt: createdAt() },t=>({idempotency:uniqueIndex('trust_events_match_player_reason_uidx').on(t.matchId,t.playerId,t.reason)}));
export const runtimeConfig = pgTable('runtime_config', { key: text('key').primaryKey(), value: jsonb('value').notNull(), description: text('description').notNull(), isPublic: boolean('is_public').notNull().default(false), updatedBy: text('updated_by').notNull().default('system'), updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull() });
export const featureFlags = pgTable('feature_flags', { key: text('key').primaryKey(), enabled: boolean('enabled').notNull().default(false), description: text('description').notNull(), updatedBy: text('updated_by').notNull().default('system'), updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull() });
export const patches = pgTable('patches', { id: uuid('id').primaryKey().defaultRandom(), version: text('version').notNull().unique(), title: jsonb('title').$type<LocalizedText>().notNull(), summary: jsonb('summary').$type<LocalizedText>().notNull(), changelog: jsonb('changelog').$type<LocalizedText>().notNull(), status: text('status').notNull().default('draft'), publishedAt: timestamp('published_at', { withTimezone: true }), createdAt: createdAt(), updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull() });
export const sanctions = pgTable('sanctions', { id: uuid('id').primaryKey().defaultRandom(), playerId: uuid('player_id').references(() => players.id).notNull(), type: text('type').notNull(), reason: text('reason').notNull(), expiresAt: timestamp('expires_at', { withTimezone: true }), createdBy: text('created_by').notNull(), createdAt: createdAt(), revokedAt: timestamp('revoked_at', { withTimezone: true }) }, (t) => ({ active: index('sanctions_active_idx').on(t.playerId, t.revokedAt) }));
export const auditLogs = pgTable('audit_logs', { id: uuid('id').primaryKey().defaultRandom(), actorType: text('actor_type').notNull(), actorId: text('actor_id').notNull(), action: text('action').notNull(), entityType: text('entity_type').notNull(), entityId: text('entity_id').notNull(), oldValue: jsonb('old_value'), newValue: jsonb('new_value'), ipAddress: text('ip_address'), createdAt: createdAt() }, (t) => ({ created: index('audit_created_idx').on(t.createdAt) }));
