import type { FastifyInstance } from 'fastify';
import type pg from 'pg';
import { ApiError } from '../shared/errors.js';
import { abilitySchema, entrySchema, heroCreateSchema, heroPatchSchema, patchSchema } from './validation.js';
import { BalancePatchService } from './service.js';

const editable=['draft','in_review','approved','scheduled'];
const nested:{[k:string]:{table:string,data:string}}={facets:{table:'balance_facets',data:'facet_data'},talents:{table:'balance_talents',data:'talent_data'},upgrades:{table:'balance_upgrades',data:'upgrade_data'}};
const camel=(row:any)=>Object.fromEntries(Object.entries(row??{}).map(([k,v])=>[k.replace(/_([a-z])/g,(_,c)=>c.toUpperCase()),v]));
const rows=(r:pg.QueryResult)=>r.rows.map(camel);
export function registerBalanceRoutes(app:FastifyInstance,pool:pg.Pool){
 const service=new BalancePatchService(pool);
 const actor=()=> 'bootstrap'; // Existing single administrator is the bootstrap owner.
 app.get('/v1/admin/balance/dashboard',async()=>camel((await pool.query(`select (select count(*) from balance_heroes where status<>'archived') heroes,(select count(*) from balance_abilities where status<>'archived') abilities,(select count(*) from balance_patches where status='draft') drafts,(select count(*) from balance_patches where status='in_review') in_review,(select version from balance_patches where status='published' and release_channel='production' order by published_at desc limit 1) current_version`)).rows[0]));
 app.get('/v1/admin/balance/heroes',async(req:any)=>({heroes:rows(await pool.query(`select * from balance_heroes where ($1::text is null or status=$1) order by sort_order,name_en limit 500`,[req.query?.status??null]))}));
 app.post('/v1/admin/balance/heroes',async(req:any,rep)=>{const b=heroCreateSchema.parse(req.body);const q=await pool.query(`insert into balance_heroes(external_id,slug,name_en,name_ru,short_name,primary_attribute,attack_type,roles,tags,portrait_url,icon_url,status,sort_order,current_data,created_by,updated_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$15) returning *`,[b.externalId??null,b.slug,b.nameEn,b.nameRu,b.shortName??null,b.primaryAttribute,b.attackType,b.roles,b.tags,b.portraitUrl??null,b.iconUrl??null,b.status,b.sortOrder,b.currentData,actor()]);await audit(pool,'hero_created','hero',q.rows[0].id,null,q.rows[0]);rep.status(201);return {hero:camel(q.rows[0])}});
 app.get('/v1/admin/balance/heroes/:id',async(req:any)=>{const h=(await pool.query('select * from balance_heroes where id=$1',[req.params.id])).rows[0];if(!h)throw new ApiError(404,'HERO_NOT_FOUND','Hero not found');const [abilities,facets,talents,upgrades]=await Promise.all(['abilities','facets','talents','upgrades'].map(x=>pool.query(`select * from balance_${x} where hero_id=$1 order by id`,[h.id])));return {hero:camel(h),abilities:rows(abilities),facets:rows(facets),talents:rows(talents),upgrades:rows(upgrades)}});
 app.patch('/v1/admin/balance/heroes/:id',async(req:any)=>{const b=heroPatchSchema.parse(req.body);const old=(await pool.query('select * from balance_heroes where id=$1',[req.params.id])).rows[0];if(!old)throw new ApiError(404,'HERO_NOT_FOUND','Hero not found');const merged=heroCreateSchema.parse({...camel(old),...b,currentData:b.currentData??old.current_data});const q=await pool.query(`update balance_heroes set external_id=$3,slug=$4,name_en=$5,name_ru=$6,short_name=$7,primary_attribute=$8,attack_type=$9,roles=$10,tags=$11,portrait_url=$12,icon_url=$13,status=$14,sort_order=$15,current_data=$16,updated_by=$17,updated_at=now(),row_version=row_version+1 where id=$1 and row_version=$2 returning *`,[req.params.id,b.rowVersion,merged.externalId??null,merged.slug,merged.nameEn,merged.nameRu,merged.shortName??null,merged.primaryAttribute,merged.attackType,merged.roles,merged.tags,merged.portraitUrl??null,merged.iconUrl??null,merged.status,merged.sortOrder,merged.currentData,actor()]);if(!q.rows[0])throw new ApiError(409,'BALANCE_VERSION_CONFLICT','Hero was updated concurrently');await audit(pool,'hero_updated','hero',old.id,old,q.rows[0]);return {hero:camel(q.rows[0])}});
 for(const [action,status] of [['archive','archived'],['restore','active']] as const)app.post(`/v1/admin/balance/heroes/:id/${action}`,async(req:any)=>{const q=await pool.query('update balance_heroes set status=$2,row_version=row_version+1,updated_at=now(),updated_by=$3 where id=$1 returning *',[req.params.id,status,actor()]);if(!q.rows[0])throw new ApiError(404,'HERO_NOT_FOUND','Hero not found');await audit(pool,action==='archive'?'hero_archived':'hero_updated','hero',q.rows[0].id,null,q.rows[0]);return {hero:camel(q.rows[0])}});
 app.post('/v1/admin/balance/heroes/:id/duplicate',async(req:any)=>{const suffix=String(req.body?.slug??'').trim();if(!suffix)throw new ApiError(400,'SLUG_REQUIRED','A new slug is required');const q=await pool.query(`insert into balance_heroes(external_id,slug,name_en,name_ru,short_name,primary_attribute,attack_type,roles,tags,portrait_url,icon_url,status,sort_order,current_data,created_by,updated_by) select null,$2,name_en||' Copy',name_ru||' Копия',short_name,primary_attribute,attack_type,roles,tags,portrait_url,icon_url,'hidden',sort_order,current_data,$3,$3 from balance_heroes where id=$1 returning *`,[req.params.id,suffix,actor()]);if(!q.rows[0])throw new ApiError(404,'HERO_NOT_FOUND','Hero not found');return {hero:camel(q.rows[0])}});
 app.post('/v1/admin/balance/heroes/:id/abilities',async(req:any,rep)=>{const b=abilitySchema.parse(req.body);const q=await pool.query(`insert into balance_abilities(hero_id,slug,name_en,name_ru,description_en,description_ru,type,slot,max_level,behavior,damage_type,target_type,dispel_type,pierces_debuff_immunity,icon_url,status,ability_data) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) returning *`,[req.params.id,b.slug,b.nameEn,b.nameRu,b.descriptionEn,b.descriptionRu,b.type,b.slot,b.maxLevel,b.behavior,b.damageType,b.targetType,b.dispelType??null,b.piercesDebuffImmunity,b.iconUrl??null,b.status,b.abilityData]);rep.status(201);return {ability:camel(q.rows[0])}});
 app.patch('/v1/admin/balance/abilities/:id',async(req:any)=>{const old=(await pool.query('select * from balance_abilities where id=$1',[req.params.id])).rows[0];if(!old)throw new ApiError(404,'ABILITY_NOT_FOUND','Ability not found');const rowVersion=Number(req.body?.rowVersion),b=abilitySchema.parse({...camel(old),...req.body,abilityData:req.body?.abilityData??old.ability_data});const q=await pool.query(`update balance_abilities set slug=$3,name_en=$4,name_ru=$5,description_en=$6,description_ru=$7,type=$8,slot=$9,max_level=$10,behavior=$11,damage_type=$12,target_type=$13,dispel_type=$14,pierces_debuff_immunity=$15,icon_url=$16,status=$17,ability_data=$18,row_version=row_version+1,updated_at=now() where id=$1 and row_version=$2 returning *`,[req.params.id,rowVersion,b.slug,b.nameEn,b.nameRu,b.descriptionEn,b.descriptionRu,b.type,b.slot,b.maxLevel,b.behavior,b.damageType,b.targetType,b.dispelType??null,b.piercesDebuffImmunity,b.iconUrl??null,b.status,b.abilityData]);if(!q.rows[0])throw new ApiError(409,'BALANCE_VERSION_CONFLICT','Ability was updated concurrently');await audit(pool,'ability_updated','ability',req.params.id,old,q.rows[0]);return {ability:camel(q.rows[0])}});
 app.post('/v1/admin/balance/abilities/:id/archive',async(req:any)=>({ability:camel((await pool.query(`update balance_abilities set status='archived',row_version=row_version+1,updated_at=now() where id=$1 returning *`,[req.params.id])).rows[0])}));
 for(const [resource,meta] of Object.entries(nested)){app.get(`/v1/admin/balance/heroes/:id/${resource}`,async(req:any)=>({[resource]:rows(await pool.query(`select * from ${meta.table} where hero_id=$1 order by id`,[req.params.id]))}));app.post(`/v1/admin/balance/heroes/:id/${resource}`,async(req:any)=>{const b=req.body??{};return {[resource.slice(0,-1)]:camel((await pool.query(`insert into ${meta.table}(hero_id,${resource==='facets'?'slug,':''}name_en,name_ru,description_en,description_ru,${resource==='talents'?'tier,side,':resource==='upgrades'?'ability_id,type,':''}${meta.data}${resource==='facets'?',status,sort_order':''}) values($1,${resource==='facets'?'$2,':''}$3,$4,$5,$6,${resource==='talents'?'$7,$8,':resource==='upgrades'?'$7,$8,':''}$9${resource==='facets'?',coalesce($10,\'active\'),coalesce($11,0)':''}) returning *`,[req.params.id,b.slug,b.nameEn,b.nameRu,b.descriptionEn,b.descriptionRu,b.tier??b.abilityId,b.side??b.type,b[meta.data.replace(/_([a-z])/g,(_,c)=>c.toUpperCase())]??{},b.status,b.sortOrder])).rows[0])}});app.patch(`/v1/admin/balance/${resource}/:id`,async(req:any)=>{const b=req.body??{};const q=await pool.query(`update ${meta.table} set name_en=coalesce($2,name_en),name_ru=coalesce($3,name_ru),description_en=coalesce($4,description_en),description_ru=coalesce($5,description_ru),${meta.data}=coalesce($6,${meta.data}),updated_at=now() where id=$1 returning *`,[req.params.id,b.nameEn,b.nameRu,b.descriptionEn,b.descriptionRu,b[meta.data.replace(/_([a-z])/g,(_,c)=>c.toUpperCase())]]);return {[resource.slice(0,-1)]:camel(q.rows[0])}});app.delete(`/v1/admin/balance/${resource}/:id`,async(req:any)=>{await pool.query(`delete from ${meta.table} where id=$1`,[req.params.id]);return {deleted:true}})}
 app.get('/v1/admin/balance/patches',async()=>({patches:rows(await pool.query('select * from balance_patches order by created_at desc'))}));
 app.post('/v1/admin/balance/patches',async(req:any,rep)=>{const b=patchSchema.parse(req.body);const q=await pool.query(`insert into balance_patches(slug,version,title_en,title_ru,summary_en,summary_ru,release_channel,created_by) values($1,$2,$3,$4,$5,$6,$7,$8) returning *`,[b.slug,b.version,b.titleEn,b.titleRu,b.summaryEn,b.summaryRu,b.releaseChannel,actor()]);await audit(pool,'patch_created','balance_patch',q.rows[0].id,null,q.rows[0]);rep.status(201);return {patch:camel(q.rows[0])}});
 app.get('/v1/admin/balance/patches/:id',async(req:any)=>patchDetail(pool,req.params.id));
 app.patch('/v1/admin/balance/patches/:id',async(req:any)=>{const p=(await pool.query('select * from balance_patches where id=$1',[req.params.id])).rows[0];if(!p)throw new ApiError(404,'BALANCE_PATCH_NOT_FOUND','Balance patch not found');if(!editable.includes(p.status)||p.status!=='draft')throw new ApiError(409,'IMMUTABLE_PATCH','Only draft patches can be edited');if(p.row_version!==req.body?.rowVersion)throw new ApiError(409,'BALANCE_VERSION_CONFLICT','Patch was updated concurrently');const b=patchSchema.parse({...camel(p),...req.body});const q=await pool.query(`update balance_patches set slug=$2,version=$3,title_en=$4,title_ru=$5,summary_en=$6,summary_ru=$7,release_channel=$8,row_version=row_version+1,updated_at=now() where id=$1 returning *`,[p.id,b.slug,b.version,b.titleEn,b.titleRu,b.summaryEn,b.summaryRu,b.releaseChannel]);return {patch:camel(q.rows[0])}});
 app.post('/v1/admin/balance/patches/:id/entries',async(req:any)=>{await assertDraft(pool,req.params.id);const b=entrySchema.parse(req.body);const q=await pool.query(`insert into balance_patch_entries(patch_id,entity_type,entity_id,operation,before_data,after_data,category,title_en,title_ru,description_en,description_ru,sort_order) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) returning *`,[req.params.id,b.entityType,b.entityId??null,b.operation,b.beforeData??null,b.afterData??null,b.category,b.titleEn,b.titleRu,b.descriptionEn,b.descriptionRu,b.sortOrder]);return {entry:camel(q.rows[0])}});
 app.patch('/v1/admin/balance/patches/:id/entries/:entryId',async(req:any)=>{await assertDraft(pool,req.params.id);const b=entrySchema.parse(req.body);const q=await pool.query(`update balance_patch_entries set entity_type=$3,entity_id=$4,operation=$5,before_data=$6,after_data=$7,category=$8,title_en=$9,title_ru=$10,description_en=$11,description_ru=$12,sort_order=$13,updated_at=now() where id=$1 and patch_id=$2 returning *`,[req.params.entryId,req.params.id,b.entityType,b.entityId??null,b.operation,b.beforeData??null,b.afterData??null,b.category,b.titleEn,b.titleRu,b.descriptionEn,b.descriptionRu,b.sortOrder]);return {entry:camel(q.rows[0])}});
 app.delete('/v1/admin/balance/patches/:id/entries/:entryId',async(req:any)=>{await assertDraft(pool,req.params.id);await pool.query('delete from balance_patch_entries where id=$1 and patch_id=$2',[req.params.entryId,req.params.id]);return {deleted:true}});
 app.get('/v1/admin/balance/patches/:id/diff',async(req:any)=>({entries:rows(await pool.query('select * from balance_patch_entries where patch_id=$1 order by sort_order,id',[req.params.id]))}));
 app.post('/v1/admin/balance/patches/:id/validate',async(req:any)=>service.validation.validatePatch(req.params.id));
 for(const [action,to] of [['submit','in_review'],['return-to-draft','draft'],['approve','approved']] as const)app.post(`/v1/admin/balance/patches/:id/${action}`,async(req:any)=>service.transition(req.params.id,to,Number(req.body?.rowVersion),actor()));
 app.post('/v1/admin/balance/patches/:id/schedule',async(req:any)=>service.transition(req.params.id,'scheduled',Number(req.body?.rowVersion),actor(),new Date(req.body?.scheduledAt)));
 app.post('/v1/admin/balance/patches/:id/publish',async(req:any)=>service.publish(req.params.id,Number(req.body?.rowVersion),actor()));
 app.post('/v1/admin/balance/patches/:id/rollback',async(req:any)=>service.rollback(req.params.id,actor()));
 app.post('/v1/admin/balance/import/validate',async(req:any)=>importBalance(pool,service,req.body,true));app.post('/v1/admin/balance/import/apply',async(req:any)=>importBalance(pool,service,req.body,false));
 app.get('/v1/admin/balance/export',async()=>({schemaVersion:'1.0',exportedAt:new Date(),heroes:rows(await pool.query('select * from balance_heroes order by sort_order,name_en'))}));
 app.get('/v1/admin/balance/audit',async()=>({audit:rows(await pool.query(`select * from audit_logs where entity_type like 'balance%' or action like 'hero_%' or action like 'ability_%' or action like 'patch_%' order by created_at desc limit 500`))}));
 app.get('/v1/public/balance/current',async()=>({patch:camel((await pool.query(`select id,slug,version,title_en,title_ru,summary_en,summary_ru,published_at from balance_patches where status='published' and release_channel='production' order by published_at desc limit 1`)).rows[0]??null)}));
 app.get('/v1/public/balance/heroes',async()=>({heroes:rows(await pool.query(`select id,slug,name_en,name_ru,short_name,primary_attribute,attack_type,roles,tags,portrait_url,icon_url,sort_order,current_data from balance_heroes where status='active' order by sort_order,name_en`))}));
 app.get('/v1/public/balance/heroes/:slug',async(req:any)=>{const h=(await pool.query(`select id,slug,name_en,name_ru,short_name,primary_attribute,attack_type,roles,tags,portrait_url,icon_url,current_data from balance_heroes where slug=$1 and status='active'`,[req.params.slug])).rows[0];if(!h)throw new ApiError(404,'HERO_NOT_FOUND','Hero not found');return {hero:camel(h),abilities:rows(await pool.query(`select slug,name_en,name_ru,description_en,description_ru,type,slot,max_level,behavior,damage_type,target_type,dispel_type,pierces_debuff_immunity,icon_url,ability_data from balance_abilities where hero_id=$1 and status='active' order by slot`,[h.id]))}});
 app.get('/v1/public/patches',async()=>({patches:rows(await pool.query(`select slug,version,title_en,title_ru,summary_en,summary_ru,published_at from balance_patches where status in ('published','superseded') and release_channel='production' order by published_at desc`))}));
 app.get('/v1/public/patches/:slug',async(req:any)=>publicPatch(pool,req.params.slug));app.get('/v1/public/patches/:slug/diff',async(req:any)=>publicPatch(pool,req.params.slug));
 return service;
}
async function patchDetail(pool:pg.Pool,id:string){const p=(await pool.query('select * from balance_patches where id=$1',[id])).rows[0];if(!p)throw new ApiError(404,'BALANCE_PATCH_NOT_FOUND','Balance patch not found');return {patch:camel(p),entries:rows(await pool.query('select * from balance_patch_entries where patch_id=$1 order by sort_order,id',[id])),snapshots:rows(await pool.query('select * from balance_snapshots where patch_id=$1',[id]))}}
async function assertDraft(pool:pg.Pool,id:string){const p=(await pool.query('select status from balance_patches where id=$1',[id])).rows[0];if(!p)throw new ApiError(404,'BALANCE_PATCH_NOT_FOUND','Balance patch not found');if(p.status!=='draft')throw new ApiError(409,'IMMUTABLE_PATCH','Patch entries are immutable outside draft')}
async function publicPatch(pool:pg.Pool,slug:string){const p=(await pool.query(`select id,slug,version,title_en,title_ru,summary_en,summary_ru,published_at from balance_patches where slug=$1 and status in ('published','superseded') and release_channel='production'`,[slug])).rows[0];if(!p)throw new ApiError(404,'PATCH_NOT_FOUND','Published patch not found');return {patch:camel(p),entries:rows(await pool.query(`select entity_type,entity_id,operation,category,title_en,title_ru,description_en,description_ru,before_data,after_data,sort_order from balance_patch_entries where patch_id=$1 order by sort_order,id`,[p.id]))}}
async function audit(pool:pg.Pool,action:string,type:string,id:string,oldValue:any,newValue:any){await pool.query(`insert into audit_logs(actor_type,actor_id,action,entity_type,entity_id,old_value,new_value) values('admin','bootstrap',$1,$2,$3,$4,$5)`,[action,type,id,oldValue,newValue])}
async function importBalance(pool:pg.Pool,service:BalancePatchService,input:any,dryRun:boolean){if(input?.schemaVersion!=='1.0'||!Array.isArray(input.heroes))throw new ApiError(400,'INVALID_IMPORT_SCHEMA','schemaVersion 1.0 and heroes are required');if(JSON.stringify(input).length>1_000_000)throw new ApiError(413,'IMPORT_TOO_LARGE','Import is limited to 1MB');const errors:any[]=[];input.heroes.forEach((h:any,i:number)=>{const r=heroCreateSchema.safeParse(h);if(!r.success)errors.push({row:i+1,issues:r.error.issues})});const hash=service.hash(input);if(!dryRun&&!input.dryRunJobId)throw new ApiError(409,'DRY_RUN_REQUIRED','A successful dry-run job is required');if(!dryRun){const prior=(await pool.query(`select * from balance_import_jobs where id=$1 and dry_run=true and status='validated' and payload_hash=$2`,[input.dryRunJobId,hash])).rows[0];if(!prior)throw new ApiError(409,'DRY_RUN_MISMATCH','Dry-run does not match this payload');if(errors.length)throw new ApiError(422,'IMPORT_VALIDATION_FAILED','Import has validation errors')}const job=(await pool.query(`insert into balance_import_jobs(status,schema_version,dry_run,payload_hash,total_rows,valid_rows,invalid_rows,errors,created_by,completed_at) values($1,'1.0',$2,$3,$4,$5,$6,$7,'bootstrap',now()) returning *`,[dryRun?'validated':'completed',dryRun,hash,input.heroes.length,input.heroes.length-errors.length,errors.length,JSON.stringify(errors)])).rows[0];if(!dryRun)for(const h of input.heroes){const b=heroCreateSchema.parse(h);await pool.query(`insert into balance_heroes(slug,name_en,name_ru,primary_attribute,attack_type,roles,tags,status,sort_order,current_data,created_by,updated_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'bootstrap','bootstrap') on conflict(slug) do update set name_en=excluded.name_en,name_ru=excluded.name_ru,current_data=excluded.current_data,updated_at=now(),row_version=balance_heroes.row_version+1`,[b.slug,b.nameEn,b.nameRu,b.primaryAttribute,b.attackType,b.roles,b.tags,b.status,b.sortOrder,b.currentData])}return {job:camel(job),valid:!errors.length,errors}}
