import { randomUUID, createHash } from 'crypto';
import type pg from 'pg';
import { ApiError } from '../shared/errors.js';
import type { ValidationIssue } from './validation.js';

const transitions:Record<string,string[]>={draft:['in_review'],in_review:['draft','approved'],approved:['scheduled','published'],scheduled:['published'],published:['superseded']};
const tables:Record<string,string>={hero:'balance_heroes',ability:'balance_abilities',facet:'balance_facets',talent:'balance_talents',upgrade:'balance_upgrades'};
export class BalanceValidationService {
  constructor(private pool:pg.Pool){}
  async validatePatch(id:string){const issues:ValidationIssue[]=[];const patch=(await this.pool.query('select * from balance_patches where id=$1',[id])).rows[0];if(!patch)throw new ApiError(404,'BALANCE_PATCH_NOT_FOUND','Balance patch not found');const entries=(await this.pool.query('select * from balance_patch_entries where patch_id=$1',[id])).rows;if(!entries.length)issues.push({severity:'error',code:'EMPTY_PATCH',message:'Patch must contain at least one entry'});for(const e of entries){if(e.entity_type!=='system'&&!tables[e.entity_type])issues.push({severity:'error',code:'INVALID_ENTITY_TYPE',message:`Unsupported entity type ${e.entity_type}`});if(e.operation!=='archive'&&!e.after_data)issues.push({severity:'error',code:'AFTER_DATA_REQUIRED',message:'afterData is required',path:e.id});}const incomplete=(await this.pool.query(`select tier from balance_talents group by hero_id,tier having count(*)<>2`)).rows;if(incomplete.length)issues.push({severity:'warning',code:'INCOMPLETE_TALENT_TIER',message:'A populated talent tier should contain left and right talents'});return {valid:!issues.some(i=>i.severity==='error'),issues};}
  assertTransition(from:string,to:string){if(!transitions[from]?.includes(to))throw new ApiError(409,'INVALID_BALANCE_PATCH_TRANSITION',`Cannot transition patch from ${from} to ${to}`);}
}
export class BalancePatchService {
  validation:BalanceValidationService;
  constructor(private pool:pg.Pool){this.validation=new BalanceValidationService(pool)}
  async transition(id:string,to:string,rowVersion:number,actor='bootstrap',scheduledAt?:Date){const c=await this.pool.connect();try{await c.query('begin');const p=(await c.query('select * from balance_patches where id=$1 for update',[id])).rows[0];if(!p)throw new ApiError(404,'BALANCE_PATCH_NOT_FOUND','Balance patch not found');if(p.status===to){await c.query('commit');return {patch:p,idempotent:true}}this.validation.assertTransition(p.status,to);if(p.row_version!==rowVersion)throw new ApiError(409,'BALANCE_VERSION_CONFLICT','Patch was updated concurrently');const fields:any={};if(to==='in_review')fields.reviewed_by=actor;if(to==='approved')fields.approved_by=actor;if(to==='scheduled'){if(!scheduledAt||scheduledAt<=new Date())throw new ApiError(400,'INVALID_SCHEDULE','scheduledAt must be in the future');fields.scheduled_at=scheduledAt}const set=Object.keys(fields).map((k,i)=>`${k}=$${i+4}`).join(',');const q=`update balance_patches set status=$2,row_version=row_version+1,updated_at=now()${set?','+set:''} where id=$1 and row_version=$3 returning *`;const next=(await c.query(q,[id,to,rowVersion,...Object.values(fields)])).rows[0];await this.audit(c,`patch_${to==='in_review'?'submitted':to}`,'balance_patch',id,p,next,actor);await c.query('commit');return {patch:next,idempotent:false}}catch(e){await c.query('rollback');throw e}finally{c.release()}}
  async publish(id:string,rowVersion:number,actor='bootstrap'){const c=await this.pool.connect();try{await c.query('begin');await c.query(`select pg_advisory_xact_lock(hashtext('trust_balance_publish'))`);const p=(await c.query('select * from balance_patches where id=$1 for update',[id])).rows[0];if(!p)throw new ApiError(404,'BALANCE_PATCH_NOT_FOUND','Balance patch not found');if(p.status==='published'){await c.query('commit');return {patch:p,idempotent:true}}this.validation.assertTransition(p.status,'published');if(p.row_version!==rowVersion)throw new ApiError(409,'BALANCE_VERSION_CONFLICT','Patch was updated concurrently');const result=await this.validation.validatePatch(id);if(!result.valid)throw new ApiError(422,'BALANCE_VALIDATION_FAILED',result.issues.filter(x=>x.severity==='error').map(x=>x.message).join('; '));const entries=(await c.query('select * from balance_patch_entries where patch_id=$1 order by sort_order,id',[id])).rows;for(const e of entries){if(e.entity_type==='system')continue;const table=tables[e.entity_type]!;if(e.entity_id){const before=(await c.query(`select to_jsonb(x) data from ${table} x where id=$1 for update`,[e.entity_id])).rows[0]?.data??e.before_data;if(before)await c.query('insert into balance_snapshots(patch_id,entity_type,entity_id,data) values($1,$2,$3,$4)',[id,e.entity_type,e.entity_id,before]);if(e.operation==='archive')await c.query(`update ${table} set status='archived',updated_at=now() where id=$1`,[e.entity_id]);else if(e.operation==='restore')await c.query(`update ${table} set status='active',updated_at=now() where id=$1`,[e.entity_id]);else if(e.operation==='update')await c.query(`update ${table} set current_data=coalesce($2->'currentData',$2->'current_data',current_data),row_version=row_version+1,updated_at=now() where id=$1`,[e.entity_id,e.after_data]);}}
    if(p.release_channel==='production')await c.query(`update balance_patches set status='superseded',updated_at=now() where status='published' and release_channel='production' and id<>$1`,[id]);const next=(await c.query(`update balance_patches set status='published',published_at=now(),published_by=$2,row_version=row_version+1,updated_at=now() where id=$1 returning *`,[id,actor])).rows[0];await this.audit(c,'patch_published','balance_patch',id,p,next,actor);await c.query('commit');return {patch:next,idempotent:false}}catch(e){await c.query('rollback');throw e}finally{c.release()}}
  async rollback(id:string,actor='bootstrap'){const c=await this.pool.connect();try{await c.query('begin');const p=(await c.query(`select * from balance_patches where id=$1 and status in ('published','superseded') for update`,[id])).rows[0];if(!p)throw new ApiError(409,'PATCH_NOT_ROLLBACKABLE','Only published history can be rolled back');const rollback=(await c.query(`insert into balance_patches(slug,version,title_en,title_ru,summary_en,summary_ru,status,release_channel,rollback_of_patch_id,created_by) values($1,$2,$3,$4,$5,$6,'draft',$7,$8,$9) returning *`,[`${p.slug}-rollback-${Date.now()}`,`${p.version}-rollback-${Date.now()}`,'Rollback '+p.title_en,'Откат '+p.title_ru,'Compensating TRUST balance patch','Компенсирующий патч баланса TRUST',p.release_channel,id,actor])).rows[0];await c.query(`insert into balance_patch_entries(patch_id,entity_type,entity_id,operation,before_data,after_data,category,title_en,title_ru,description_en,description_ru,sort_order) select $1,entity_type,entity_id,case operation when 'archive' then 'restore' when 'restore' then 'archive' else 'update' end,after_data,before_data,category,'Rollback: '||title_en,'Откат: '||title_ru,description_en,description_ru,sort_order from balance_patch_entries where patch_id=$2 order by sort_order`,[rollback.id,id]);await this.audit(c,'patch_rolled_back','balance_patch',rollback.id,p,rollback,actor);await c.query('commit');return {patch:rollback}}catch(e){await c.query('rollback');throw e}finally{c.release()}}
  async publishDue(log:{error:(x:unknown,m:string)=>void}){const due=(await this.pool.query(`select id,row_version from balance_patches where status='scheduled' and scheduled_at<=now() order by scheduled_at limit 20`)).rows;for(const p of due)try{await this.publish(p.id,p.row_version,'scheduler')}catch(error){log.error({error,patchId:p.id},'scheduled balance publish failed')}}
  hash(input:unknown){return createHash('sha256').update(JSON.stringify(input)).digest('hex')}
  private audit(c:pg.PoolClient,action:string,type:string,id:string,oldValue:unknown,newValue:unknown,actor:string){return c.query(`insert into audit_logs(actor_type,actor_id,action,entity_type,entity_id,old_value,new_value) values('admin',$1,$2,$3,$4,$5,$6)`,[actor,action,type,id,oldValue,newValue])}
}
export const newId=()=>randomUUID();
