import Fastify from 'fastify';import cookie from '@fastify/cookie';import cors from '@fastify/cors';import helmet from '@fastify/helmet';import rateLimit from '@fastify/rate-limit';import { randomUUID, timingSafeEqual } from 'crypto';import { Server as SocketIOServer } from 'socket.io';import { eq, and, sql, desc } from 'drizzle-orm';import type { Env } from './config/env.js';import { SERVICE_NAME,VERSION,SESSION_COOKIE,SESSION_TTL_SECONDS } from './config/constants.js';import { createDatabase } from './db/client.js';import { players,queueEntries,runtimeConfig,featureFlags,matches,matchPlayers,auditLogs,sanctions } from './db/schema.js';import { ApiError, unauthorized } from './shared/errors.js';import { devAuthSchema, joinQueueSchema } from './shared/validation.js';import { allowedRatingRange, MatchmakingWorker } from './worker/matcher.js';
type Deps={env:Env; db?:ReturnType<typeof createDatabase>; worker?:MatchmakingWorker};
const sessions=new Map<string,string>();
export async function buildApp({env,db:createDb}:Deps){const database=createDb??createDatabase(env);const app=Fastify({logger:{level:env.LOG_LEVEL,redact:['req.headers.authorization','req.headers.cookie','DATABASE_URL','SESSION_SECRET','ADMIN_API_KEY']},genReqId:()=>randomUUID(),bodyLimit:1_000_000});await app.register(helmet);await app.register(cors,{origin:env.CORS_ORIGINS.split(',').map(s=>s.trim()),credentials:true});await app.register(rateLimit,{max:120,timeWindow:'1 minute'});await app.register(cookie,{secret:env.SESSION_SECRET});app.decorate('db',database.db);app.decorate('pool',database.pool);app.decorate('io',null);
app.addHook('onRequest',async(req,_rep)=>{req.log=req.log.child({requestId:req.id});});
app.setErrorHandler((err,req,rep)=>{const e=err instanceof ApiError?err:new ApiError(500,'INTERNAL_ERROR','Internal server error');req.log.error({code:e.code,statusCode:e.statusCode,err:err instanceof ApiError?undefined:err},'request failed');void rep.status(e.statusCode).send({error:{code:e.code,message:e.message,requestId:req.id}})});
async function currentPlayer(req:any){const raw=req.unsignCookie(req.cookies[SESSION_COOKIE]??'');const sid=raw.valid?raw.value:undefined;const playerId=sid?sessions.get(sid):undefined;if(!playerId)return null;const [p]=await database.db.select().from(players).where(eq(players.id,playerId)).limit(1);return p??null}async function requirePlayer(req:any){const p=await currentPlayer(req);if(!p)throw unauthorized();return p}
app.get('/health',async()=>({status:'ok',service:SERVICE_NAME,version:VERSION,uptime:Math.floor(process.uptime())}));
app.get('/ready',async(_req,rep)=>{try{await database.pool.query('select 1');return {status:'ready',database:'ok',migrations:'ok',worker:'ok'}}catch{rep.status(503);return {status:'not_ready',database:'failed',worker:'unknown'}}});
app.post('/v1/auth/dev',async(req,rep)=>{if(!env.ALLOW_DEV_AUTH)throw new ApiError(404,'DEV_AUTH_DISABLED','Development authentication is disabled');const body=devAuthSchema.parse(req.body);const steamId=`dev:${body.displayName.toLowerCase()}`;const [p]=await database.db.insert(players).values({steamId,displayName:body.displayName,lastSeenAt:new Date()}).onConflictDoUpdate({target:players.steamId,set:{displayName:body.displayName,lastSeenAt:new Date()}}).returning();const sid=randomUUID();sessions.set(sid,p!.id);rep.setCookie(SESSION_COOKIE,sid,{httpOnly:true,sameSite:'lax',secure:env.NODE_ENV==='production',signed:true,path:'/',maxAge:SESSION_TTL_SECONDS});return {player:publicPlayer(p!)} });
app.post('/v1/auth/logout',async(req,rep)=>{const raw=req.unsignCookie(req.cookies[SESSION_COOKIE]??'');if(raw.valid&&raw.value)sessions.delete(raw.value);rep.clearCookie(SESSION_COOKIE,{path:'/'});return {ok:true}});
app.get('/v1/me',async(req)=>({player:publicPlayer(await requirePlayer(req))}));
app.get('/v1/config/public',async()=>({config:Object.fromEntries((await database.db.select().from(runtimeConfig).where(eq(runtimeConfig.isPublic,true))).map(r=>[r.key,r.value]))}));
async function cfg(key:string, fallback:any){const [r]=await database.db.select().from(runtimeConfig).where(eq(runtimeConfig.key,key)).limit(1);return r?.value??fallback}
app.post('/v1/queue/join',async(req)=>{const player=await requirePlayer(req);const body=joinQueueSchema.parse(req.body);if(!(await cfg('matchmaking_enabled',env.MATCHMAKING_ENABLED)))throw new ApiError(503,'MATCHMAKING_DISABLED','Matchmaking is temporarily unavailable');if(!(await cfg('play_button_enabled',true)))throw new ApiError(503,'PLAY_DISABLED','Play is temporarily unavailable');if(player.trustScore<Number(await cfg('minimum_trust_score',50)))throw new ApiError(403,'TRUST_SCORE_TOO_LOW','Trust score is too low');const activeSanction=await database.db.select().from(sanctions).where(and(eq(sanctions.playerId,player.id),sql`revoked_at is null and (expires_at is null or expires_at > now())`)).limit(1);if(activeSanction.length)throw new ApiError(403,'SANCTION_ACTIVE','Active sanction blocks matchmaking');const activeMatch=await database.db.select().from(matchPlayers).innerJoin(matches,eq(matchPlayers.matchId,matches.id)).where(and(eq(matchPlayers.playerId,player.id),sql`matches.status in ('accepting','ready','connecting','in_progress')`)).limit(1);if(activeMatch.length)throw new ApiError(409,'ACTIVE_MATCH_EXISTS','Player already has an active match');const existing=await database.db.select().from(queueEntries).where(and(eq(queueEntries.playerId,player.id),eq(queueEntries.status,'waiting'))).limit(1);if(existing[0])return {queue:existing[0],idempotent:true};const [entry]=await database.db.insert(queueEntries).values({playerId:player.id,region:body.region,primaryRole:body.primaryRole,secondaryRole:body.secondaryRole,ratingSnapshot:player.rating,trustScoreSnapshot:player.trustScore}).returning();app.io?.to(`player:${player.id}`).emit('queue:updated',entry);return {queue:entry}});
app.post('/v1/queue/cancel',async(req)=>{const player=await requirePlayer(req);const [entry]=await database.db.update(queueEntries).set({status:'cancelled',cancelledAt:new Date()}).where(and(eq(queueEntries.playerId,player.id),eq(queueEntries.status,'waiting'))).returning();app.io?.to(`player:${player.id}`).emit('queue:updated',entry??null);return {cancelled:Boolean(entry)}});
app.get('/v1/queue/status',async(req)=>{const player=await requirePlayer(req);const [entry]=await database.db.select().from(queueEntries).where(eq(queueEntries.playerId,player.id)).orderBy(desc(queueEntries.joinedAt)).limit(1);const range=entry?allowedRatingRange(entry.joinedAt,new Date(),Number(await cfg('initial_rating_range',150)),Number(await cfg('maximum_rating_range',700)),Number(await cfg('rating_range_growth_per_minute',25))):0;return {queue:entry??null,waitingSeconds:entry?.status==='waiting'?Math.floor((Date.now()-entry.joinedAt.getTime())/1000):0,currentRatingRange:range}});
app.get('/v1/matches/:id',async(req:any)=>{const player=await requirePlayer(req);const rows=await database.db.select().from(matchPlayers).where(and(eq(matchPlayers.matchId,req.params.id),eq(matchPlayers.playerId,player.id))).limit(1);if(!rows.length)throw new ApiError(404,'MATCH_NOT_FOUND','Match not found');const [m]=await database.db.select().from(matches).where(eq(matches.id,req.params.id));return {match:m,player:rows[0]}});
async function acceptChange(req:any,status:'accepted'|'declined'){const player=await requirePlayer(req);const id=req.params.id;return await database.db.transaction(async(tx)=>{const [m]=await tx.select().from(matches).where(eq(matches.id,id)).limit(1);if(!m)throw new ApiError(404,'MATCH_NOT_FOUND','Match not found');if(m.acceptDeadline<new Date())throw new ApiError(409,'ACCEPT_TIMEOUT','Accept deadline expired');const [mp]=await tx.select().from(matchPlayers).where(and(eq(matchPlayers.matchId,id),eq(matchPlayers.playerId,player.id))).limit(1);if(!mp)throw new ApiError(403,'NOT_MATCH_PARTICIPANT','Not a match participant');if(status==='accepted'&&mp.acceptStatus==='accepted')return {match:m,accepted:true,idempotent:true};await tx.update(matchPlayers).set({acceptStatus:status,acceptedAt:status==='accepted'?new Date():null}).where(and(eq(matchPlayers.matchId,id),eq(matchPlayers.playerId,player.id)));if(status==='declined')await tx.update(matches).set({status:'cancelled',cancelledAt:new Date()}).where(eq(matches.id,id));else{const pending=await tx.select().from(matchPlayers).where(and(eq(matchPlayers.matchId,id),sql`accept_status <> 'accepted'`));if(!pending.length)await tx.update(matches).set({status:'ready'}).where(eq(matches.id,id));}return {ok:true}})}
app.post('/v1/matches/:id/accept',async(req)=>acceptChange(req,'accepted'));app.post('/v1/matches/:id/decline',async(req)=>acceptChange(req,'declined'));
function isAdmin(req:any){const h=String(req.headers.authorization??'');const token=h.startsWith('Bearer ')?h.slice(7):'';const a=Buffer.from(token);const b=Buffer.from(env.ADMIN_API_KEY);return a.length===b.length&&timingSafeEqual(a,b)}app.addHook('preHandler',async(req)=>{if(req.url.startsWith('/v1/admin')&&!isAdmin(req))throw new ApiError(401,'ADMIN_UNAUTHORIZED','Admin authentication required')});
app.get('/v1/admin/dashboard',async()=>({players:await database.db.select({count:sql<number>`count(*)`}).from(players),queues:await database.db.select({count:sql<number>`count(*)`}).from(queueEntries)}));app.get('/v1/admin/config',async()=>({config:await database.db.select().from(runtimeConfig)}));app.patch('/v1/admin/config/:key',async(req:any)=>{const [old]=await database.db.select().from(runtimeConfig).where(eq(runtimeConfig.key,req.params.key));if(!old)throw new ApiError(404,'CONFIG_NOT_FOUND','Config key not found');const value=(req.body as any)?.value;const [next]=await database.db.update(runtimeConfig).set({value,updatedBy:'admin',updatedAt:new Date()}).where(eq(runtimeConfig.key,req.params.key)).returning();await database.db.insert(auditLogs).values({actorType:'admin',actorId:'bootstrap',action:'runtime_config.update',entityType:'runtime_config',entityId:req.params.key,oldValue:old,newValue:next,ipAddress:req.ip});if(next!.isPublic)app.io?.to('public-config').emit('config:updated',{key:next!.key,value:next!.value});return {config:next}});app.get('/v1/admin/feature-flags',async()=>({featureFlags:await database.db.select().from(featureFlags)}));app.patch('/v1/admin/feature-flags/:key',async(req:any)=>{const enabled=Boolean((req.body as any)?.enabled);const [next]=await database.db.update(featureFlags).set({enabled,updatedBy:'admin',updatedAt:new Date()}).where(eq(featureFlags.key,req.params.key)).returning();return {featureFlag:next}});app.get('/v1/admin/queues',async()=>({queues:await database.db.select().from(queueEntries).limit(100)}));app.get('/v1/admin/matches',async()=>({matches:await database.db.select().from(matches).limit(100)}));app.post('/v1/admin/matches/:id/cancel',async(req:any)=>{const [m]=await database.db.update(matches).set({status:'cancelled',cancelledAt:new Date()}).where(eq(matches.id,req.params.id)).returning();await database.db.insert(auditLogs).values({actorType:'admin',actorId:'bootstrap',action:'match.cancel',entityType:'match',entityId:req.params.id,newValue:m,ipAddress:req.ip});return {match:m}});app.get('/v1/admin/audit',async()=>({audit:await database.db.select().from(auditLogs).orderBy(desc(auditLogs.createdAt)).limit(100)}));
app.addHook('onClose',async()=>{await database.pool.end()});return app;}
export function attachSocket(app:any,server:any,env:Env){const io=new SocketIOServer(server,{cors:{origin:env.CORS_ORIGINS.split(',').map(s=>s.trim()),credentials:true},pingInterval:25000,pingTimeout:20000});io.on('connection',s=>{s.join('public-config');s.on('join:player',(id:string)=>s.join(`player:${id}`));s.on('join:match',(id:string)=>s.join(`match:${id}`));});app.io=io;return io}function publicPlayer(p:any){return {id:p.id,displayName:p.displayName,avatarUrl:p.avatarUrl,status:p.status,rating:p.rating,trustScore:p.trustScore,region:p.region,isBot:p.isBot}}
declare module 'fastify'{interface FastifyInstance{io?:SocketIOServer|null}}
