import Fastify from 'fastify';
import cookie from '@fastify/cookie';
import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import rateLimit from '@fastify/rate-limit';
import { randomUUID, timingSafeEqual } from 'crypto';
import { Server as SocketIOServer } from 'socket.io';
import { ZodError } from 'zod';
import { and, desc, eq, inArray, sql } from 'drizzle-orm';
import type { Env } from './config/env.js';
import { SERVICE_NAME, VERSION, SESSION_COOKIE, DOTA_ROLES } from './config/constants.js';
import { createDatabase } from './db/client.js';
import { auditLogs, balancePatches, featureFlags, matchPlayers, matches, patches, players, queueEntries, ratingEvents, runtimeConfig, sanctions, sessions, steamAuthStates, trustEvents } from './db/schema.js';
import { ApiError, unauthorized } from './shared/errors.js';
import { devAuthSchema, joinQueueSchema, preferencesSchema } from './shared/validation.js';
import { allowedRatingRange, balanceTeams, selectMatchRegion, type Candidate } from './worker/matcher.js';
import { buildSteamRedirect, randomToken, sha256, verifySteamResponse } from './auth/steam.js';
import { MatchLifecycleService, type Completion } from './services/match-lifecycle.js';
import { registerBalanceRoutes } from './balance/routes.js';
import { registerGameSessionRoutes } from './game-sessions/routes.js';
import { BalancePatchService } from './balance/service.js';

type Database = ReturnType<typeof createDatabase>;
type Deps = { env: Env; db?: Database };
const requiredTables = ['players', 'sessions', 'steam_auth_states', 'queue_entries', 'matches', 'match_players', 'game_sessions', 'game_session_events', 'runtime_config', 'feature_flags', 'audit_logs'];

export async function buildApp({ env, db: createDb }: Deps) {
  const database = createDb ?? createDatabase(env);
  const app = Fastify({ logger: { level: env.LOG_LEVEL, redact: ['req.headers.authorization', 'req.headers.cookie'] }, genReqId: () => randomUUID(), bodyLimit: 1_000_000 });
  await app.register(helmet);
  await app.register(cors, { origin: env.CORS_ORIGINS.split(',').map((s) => s.trim()), credentials: true });
  await app.register(rateLimit, { max: 120, timeWindow: '1 minute' });
  await app.register(cookie, { secret: env.SESSION_SECRET });
  app.decorate('db', database.db);
  app.decorate('pool', database.pool);
  app.decorate('io', null);
  const lifecycle=new MatchLifecycleService(database.pool,(event,id,payload)=>app.io?.to(`match:${id}`).emit(event,payload));

  const cookieOptions = () => ({ httpOnly: true, sameSite: 'lax' as const, secure: env.NODE_ENV === 'production', signed: false, path: '/', maxAge: env.SESSION_TTL_SECONDS });
  async function issueSession(playerId: string, req: any, rep: any) { const token=randomToken(); const expiresAt=new Date(Date.now()+env.SESSION_TTL_SECONDS*1000); await database.db.transaction(async tx=>{await tx.insert(sessions).values({playerId,tokenHash:sha256(token),expiresAt,ipAddress:req.ip,userAgent:String(req.headers['user-agent']??'').slice(0,500)});const active=await tx.select({id:sessions.id}).from(sessions).where(and(eq(sessions.playerId,playerId),sql`revoked_at is null and expires_at > now()`)).orderBy(desc(sessions.lastSeenAt));if(active.length>5)await tx.update(sessions).set({revokedAt:new Date()}).where(inArray(sessions.id,active.slice(5).map(s=>s.id)));});rep.setCookie(SESSION_COOKIE,token,cookieOptions()); }
  async function sessionFor(req:any){const token=req.cookies[SESSION_COOKIE];if(!token)return null;const [s]=await database.db.select().from(sessions).where(and(eq(sessions.tokenHash,sha256(token)),sql`revoked_at is null and expires_at > now()`)).limit(1);if(!s)return null;await database.db.update(sessions).set({lastSeenAt:new Date()}).where(eq(sessions.id,s.id));return s}
  async function currentPlayer(req: any) { const session=await sessionFor(req);if(!session)return null; const [p] = await database.db.select().from(players).where(eq(players.id, session.playerId)).limit(1); return p ?? null; }
  async function requirePlayer(req: any) { const p = await currentPlayer(req); if (!p) throw unauthorized(); return p; }
  async function cfg(key: string, fallback: any) { const [r] = await database.db.select().from(runtimeConfig).where(eq(runtimeConfig.key, key)).limit(1); return r?.value ?? fallback; }

  app.setErrorHandler((err, req, rep) => {
    const validation = err instanceof ZodError;
    const e = err instanceof ApiError
      ? err
      : validation
        ? new ApiError(400, 'VALIDATION_ERROR', 'Request payload is invalid')
        : new ApiError(500, 'INTERNAL_ERROR', 'Internal server error');
    const details = validation
      ? err.issues.map((issue) => ({ path: issue.path.join('.'), message: issue.message }))
      : undefined;
    req.log.error({ code: e.code, statusCode: e.statusCode, details, err: err instanceof ApiError || validation ? undefined : err }, 'request failed');
    void rep.status(e.statusCode).send({ error: { code: e.code, message: e.message, requestId: req.id, ...(details ? { details } : {}) } });
  });

  app.get('/health', async () => ({ status: 'ok', service: SERVICE_NAME, version: VERSION, uptime: Math.floor(process.uptime()) }));
  app.get('/ready', async (_req, rep) => { try { await database.pool.query('select 1'); const rows = await database.pool.query<{ table_name: string }>(`select table_name from information_schema.tables where table_schema='public' and table_name = any($1)`, [requiredTables]); const found = new Set(rows.rows.map((r) => r.table_name)); const missing = requiredTables.filter((t) => !found.has(t)); if (missing.length) throw new Error('missing tables'); return { status: 'ready', database: 'ok', tables: 'ok' }; } catch { rep.status(503); return { status: 'not_ready', database: 'failed' }; } });

  app.post('/v1/auth/dev', async (req, rep) => { if (!env.ALLOW_DEV_AUTH) throw new ApiError(404, 'DEV_AUTH_DISABLED', 'Development authentication is disabled'); const body = devAuthSchema.parse(req.body); const [p] = await database.db.insert(players).values({ steamId: `dev:${body.displayName.toLowerCase()}`, displayName: body.displayName, lastSeenAt: new Date() }).onConflictDoUpdate({ target: players.steamId, set: { displayName: body.displayName, lastSeenAt: new Date() } }).returning(); await issueSession(p!.id,req,rep); return { player: publicPlayer(p!) }; });
  app.post('/v1/auth/guest', { config: { rateLimit: { max: 10, timeWindow: '1 minute' } } }, async (req, rep) => { if (!env.GUEST_AUTH_ENABLED) throw new ApiError(404, 'GUEST_AUTH_DISABLED', 'Guest authentication is disabled'); const [p] = await database.db.insert(players).values({ displayName: `Guest ${randomUUID().slice(0, 6)}`, lastSeenAt: new Date() }).returning(); await issueSession(p!.id,req,rep); return { player: publicPlayer(p!) }; });
  app.get('/v1/auth/steam/start',async (_req,rep)=>{const state=randomToken();await database.db.insert(steamAuthStates).values({stateHash:sha256(state),expiresAt:new Date(Date.now()+10*60_000)});return rep.redirect(buildSteamRedirect(env.STEAM_REALM,env.STEAM_RETURN_URL,state));});
  app.get('/v1/auth/steam/callback',async (req:any,rep)=>{const state=String(req.query.state??'');const [claimed]=await database.db.update(steamAuthStates).set({usedAt:new Date()}).where(and(eq(steamAuthStates.stateHash,sha256(state)),sql`used_at is null and expires_at > now()`)).returning();if(!claimed)throw new ApiError(400,'STEAM_STATE_INVALID','Steam login state is invalid or expired');const steamId=await verifySteamResponse(req.query,env.STEAM_RETURN_URL);if(!steamId)throw new ApiError(401,'STEAM_VERIFICATION_FAILED','Steam authentication could not be verified');let summary:any={personaname:`Steam ${steamId}`,profileurl:`https://steamcommunity.com/profiles/${steamId}`};if(env.STEAM_API_KEY){const response=await fetch(`https://api.steampowered.com/ISteamUser/GetPlayerSummaries/v2/?key=${encodeURIComponent(env.STEAM_API_KEY)}&steamids=${steamId}`);if(response.ok)summary=(await response.json() as any)?.response?.players?.[0]??summary;}const guestSession=await sessionFor(req);const player=await database.db.transaction(async tx=>{const [existing]=await tx.select().from(players).where(eq(players.steamId,steamId)).limit(1);const [guest]=guestSession?await tx.select().from(players).where(eq(players.id,guestSession.playerId)).limit(1):[];let target=existing;if(!target&&guest&&!guest.steamId){[target]=await tx.update(players).set({steamId,displayName:summary.personaname,avatarUrl:summary.avatarfull,profileUrl:summary.profileurl,profileVisibility:summary.communityvisibilitystate,updatedAt:new Date()}).where(eq(players.id,guest.id)).returning();}else if(!target){[target]=await tx.insert(players).values({steamId,displayName:summary.personaname,avatarUrl:summary.avatarfull,profileUrl:summary.profileurl,profileVisibility:summary.communityvisibilitystate}).returning();}else await tx.update(players).set({displayName:summary.personaname,avatarUrl:summary.avatarfull,profileUrl:summary.profileurl,profileVisibility:summary.communityvisibilitystate,updatedAt:new Date()}).where(eq(players.id,target.id));if(guest&&target&&guest.id!==target.id){await tx.update(matchPlayers).set({playerId:target.id}).where(eq(matchPlayers.playerId,guest.id));await tx.update(ratingEvents).set({playerId:target.id}).where(eq(ratingEvents.playerId,guest.id));await tx.update(trustEvents).set({playerId:target.id}).where(eq(trustEvents.playerId,guest.id));await tx.update(sanctions).set({playerId:target.id}).where(eq(sanctions.playerId,guest.id));await tx.update(queueEntries).set({status:'cancelled',cancelledAt:new Date()}).where(and(eq(queueEntries.playerId,guest.id),eq(queueEntries.status,'waiting')));await tx.insert(auditLogs).values({actorType:'player',actorId:target.id,action:'account.link',entityType:'player',entityId:guest.id,ipAddress:req.ip});}if(guestSession)await tx.update(sessions).set({revokedAt:new Date()}).where(eq(sessions.id,guestSession.id));return target!;});await issueSession(player.id,req,rep);return rep.redirect(new URL('/profile',env.FRONTEND_URL).toString());});
  app.post('/v1/auth/logout', async (req, rep) => { const s=await sessionFor(req);if(s)await database.db.update(sessions).set({revokedAt:new Date()}).where(eq(sessions.id,s.id)); rep.clearCookie(SESSION_COOKIE, { path: '/' }); return { ok: true }; });
  app.post('/v1/auth/logout-all', async (req,rep)=>{const player=await requirePlayer(req);await database.db.update(sessions).set({revokedAt:new Date()}).where(and(eq(sessions.playerId,player.id),sql`revoked_at is null`));rep.clearCookie(SESSION_COOKIE,{path:'/'});return {ok:true};});
  app.get('/v1/me', async (req) => ({ player: publicPlayer(await requirePlayer(req)) }));
  app.patch('/v1/me/preferences',async(req)=>{const player=await requirePlayer(req);const body=preferencesSchema.parse(req.body);const [next]=await database.db.update(players).set({regions:body.regions,preferredRole:body.primaryRole,preferredRoles:body.roles,updatedAt:new Date()}).where(eq(players.id,player.id)).returning();return {player:publicPlayer(next!)};});
  app.get('/v1/me/matches',async(req:any)=>{const player=await requirePlayer(req);return matchHistory(database,player.id,req.query);});
  app.get('/v1/players/:id/profile',async(req:any)=>{const [player]=await database.db.select().from(players).where(eq(players.id,req.params.id)).limit(1);if(!player)throw new ApiError(404,'PLAYER_NOT_FOUND','Player not found');return {player:publicPlayer(player),...await matchHistory(database,player.id,req.query)};});

  app.get('/v1/config/public', async () => ({ config: Object.fromEntries((await database.db.select().from(runtimeConfig).where(eq(runtimeConfig.isPublic, true))).map((r) => [r.key, r.value])) }));
  app.get('/v1/patches/current',async(req:any)=>{const [patch]=await database.db.select().from(patches).where(eq(patches.status,'published')).orderBy(desc(patches.publishedAt)).limit(1);if(!patch)throw new ApiError(404,'PATCH_NOT_FOUND','No published patch');const locale=String(req.query?.locale??req.headers['accept-language']??'en').startsWith('ru')?'ru':'en';return {patch:{...patch,title:localize(patch.title,locale),summary:localize(patch.summary,locale),changelog:localize(patch.changelog,locale)}};});
  app.post('/v1/queue/join', async (req) => { const player = await requirePlayer(req); const body = joinQueueSchema.parse(req.body);if(!/^7656119\d{10}$/.test(player.steamId??''))throw new ApiError(403,'STEAM_ACCOUNT_REQUIRED','Connect a Steam account to join matchmaking'); if (!(await cfg('matchmaking_enabled', env.MATCHMAKING_ENABLED)) || !(await cfg('play_button_enabled', true))) throw new ApiError(503, 'MATCHMAKING_DISABLED', String(localize(await cfg('matchmaking_disabled_message',{en:'Matchmaking is temporarily unavailable'}),'en')));const allowed=await cfg('enabled_regions',null);if(Array.isArray(allowed)&&body.regions.some(r=>!allowed.includes(r)))throw new ApiError(400,'REGION_DISABLED','One or more selected regions are disabled'); if (player.trustScore < Number(await cfg('minimum_trust_score', 50))) throw new ApiError(403, 'TRUST_SCORE_TOO_LOW', 'Trust score is too low'); const activeSanction = await database.db.select().from(sanctions).where(and(eq(sanctions.playerId, player.id), sql`revoked_at is null and (expires_at is null or expires_at > now())`)).limit(1); if (activeSanction.length) throw new ApiError(403, 'SANCTION_ACTIVE', 'Active sanction blocks matchmaking'); const activeMatch = await database.db.select().from(matchPlayers).innerJoin(matches, eq(matchPlayers.matchId, matches.id)).where(and(eq(matchPlayers.playerId, player.id), sql`matches.status in ('accepting','ready','connecting','in_progress')`)).limit(1); if (activeMatch.length) throw new ApiError(409, 'ACTIVE_MATCH_EXISTS', 'Player already has an active match'); const existing = await database.db.select().from(queueEntries).where(and(eq(queueEntries.playerId, player.id), eq(queueEntries.status, 'waiting'))).limit(1); if (existing[0]) return { queue: existing[0], idempotent: true }; const [entry] = await database.db.insert(queueEntries).values({ playerId: player.id, regions: body.regions, primaryRole: body.primaryRole, roles: body.roles, ratingSnapshot: player.rating, trustScoreSnapshot: player.trustScore }).returning();await database.db.update(players).set({regions:body.regions,preferredRole:body.primaryRole,preferredRoles:body.roles}).where(eq(players.id,player.id)); app.io?.to(`player:${player.id}`).emit('queue:updated', entry); return { queue: entry }; });
  app.post('/v1/queue/cancel', async (req) => { const player = await requirePlayer(req); const [entry] = await database.db.update(queueEntries).set({ status: 'cancelled', cancelledAt: new Date() }).where(and(eq(queueEntries.playerId, player.id), eq(queueEntries.status, 'waiting'))).returning(); return { cancelled: Boolean(entry), queue: entry ?? null }; });
  app.get('/v1/queue/status', async (req) => { const player = await requirePlayer(req); const [entry] = await database.db.select().from(queueEntries).where(eq(queueEntries.playerId, player.id)).orderBy(desc(queueEntries.joinedAt)).limit(1); const mp = await database.db.select().from(matchPlayers).innerJoin(matches, eq(matchPlayers.matchId, matches.id)).where(and(eq(matchPlayers.playerId, player.id), sql`matches.status in ('accepting','ready','connecting','in_progress')`)).limit(1); const match = mp[0] as any; return { queue: entry ?? null, matchId: match?.matches?.id ?? null,matchRegion:match?.matches?.region??null, waitingSeconds: entry?.status === 'waiting' ? Math.floor((Date.now() - entry.joinedAt.getTime()) / 1000) : 0, currentRatingRange: entry?.status === 'waiting' ? allowedRatingRange(entry.joinedAt, new Date(), Number(await cfg('initial_rating_range', 150)), Number(await cfg('maximum_rating_range', 700)), Number(await cfg('rating_range_growth_per_minute', 25))) : 0 }; });
  app.get('/v1/matches/:id', async (req: any) => matchDto(database,req.params.id,(await requirePlayer(req)).id,true));
  app.post('/v1/matches/:id/accept', async (req:any) => lifecycle.accept(req.params.id,(await requirePlayer(req)).id));
  app.post('/v1/matches/:id/decline', async (req:any) => lifecycle.decline(req.params.id,(await requirePlayer(req)).id,String(req.body?.reason??'Player declined')));
  app.post('/v1/matches/:id/connection/start',async(req:any)=>{const player=await requirePlayer(req);await assertParticipant(database,req.params.id,player.id);return lifecycle.beginConnecting(req.params.id,{type:'player',id:player.id})});
  app.post('/v1/matches/:id/connection/ready',async(req:any)=>lifecycle.connectionReady(req.params.id,(await requirePlayer(req)).id));
  app.get('/v1/me/state',async(req:any)=>{const player=await requirePlayer(req);const active=(await database.pool.query(`select m.id from matches m join match_players mp on mp.match_id=m.id where mp.player_id=$1 and m.status in('accepting','ready','connecting','in_progress') order by m.created_at desc limit 1`,[player.id])).rows[0];const queue=active?null:(await database.db.select().from(queueEntries).where(and(eq(queueEntries.playerId,player.id),eq(queueEntries.status,'waiting'))).limit(1))[0]??null;return {player:publicPlayer(player),queue,activeMatch:active?await matchDto(database,active.id,player.id,true):null}});

  function isAdmin(req: any) { const h = String(req.headers.authorization ?? ''); const token = h.startsWith('Bearer ') ? h.slice(7) : ''; const a = Buffer.from(token); const b = Buffer.from(env.ADMIN_API_KEY); return a.length === b.length && timingSafeEqual(a, b); }
  app.addHook('preHandler', async (req) => { if (req.url.startsWith('/v1/admin') && !isAdmin(req)) throw new ApiError(401, 'ADMIN_UNAUTHORIZED', 'Admin authentication required'); });
  registerGameSessionRoutes(app,database.pool,lifecycle);
  registerBalanceRoutes(app,database.pool);
  app.get('/v1/admin/dashboard', async () => adminDashboard(database));
  app.get('/v1/admin/stats',async(req:any)=>adminStats(database,String(req.query?.range??'24h')));
  app.get('/v1/admin/players',async()=>({players:await database.db.select({id:players.id,steamId:players.steamId,displayName:players.displayName,status:players.status,rating:players.rating,trustScore:players.trustScore,createdAt:players.createdAt}).from(players).limit(100)}));
  app.get('/v1/admin/players/:id',async(req:any)=>({player:(await database.db.select().from(players).where(eq(players.id,req.params.id)).limit(1))[0]??null,sanctions:await database.db.select().from(sanctions).where(eq(sanctions.playerId,req.params.id))}));
  app.post('/v1/admin/players/:id/trust-score',async(req:any)=>{const reason=String(req.body?.reason??'').trim(),value=Number(req.body?.value);if(!reason||!Number.isInteger(value)||value<0||value>100)throw new ApiError(400,'INVALID_TRUST_CHANGE','A valid value and reason are required');const [old]=await database.db.select().from(players).where(eq(players.id,req.params.id));if(!old)throw new ApiError(404,'PLAYER_NOT_FOUND','Player not found');const [next]=await database.db.update(players).set({trustScore:value}).where(eq(players.id,old.id)).returning();await database.db.insert(trustEvents).values({playerId:old.id,reason,delta:value-old.trustScore,valueBefore:old.trustScore,valueAfter:value});await audit('trust_score.update','player',old.id,old,next,req);return {player:publicPlayer(next!)};});
  app.post('/v1/admin/sanctions',async(req:any)=>{const body=req.body??{};const [row]=await database.db.insert(sanctions).values({playerId:body.playerId,type:body.type,reason:body.reason,expiresAt:body.expiresAt?new Date(body.expiresAt):null,createdBy:'admin'}).returning();await audit('sanction.create','sanction',row!.id,null,row,req);return {sanction:row};});
  app.get('/v1/admin/patches',async()=>({patches:await database.db.select().from(patches).orderBy(desc(patches.createdAt))}));
  app.post('/v1/admin/patches',async(req:any)=>{const [row]=await database.db.insert(patches).values(req.body).returning();await audit('patch.create','patch',row!.id,null,row,req);return {patch:row};});
  app.patch('/v1/admin/patches/:id',async(req:any)=>{const [old]=await database.db.select().from(patches).where(eq(patches.id,req.params.id));const [row]=await database.db.update(patches).set({...req.body,updatedAt:new Date()}).where(eq(patches.id,req.params.id)).returning();await audit('patch.update','patch',req.params.id,old,row,req);return {patch:row};});
  for(const [suffix,status] of [['publish','published'],['archive','archived']] as const)app.post(`/v1/admin/patches/:id/${suffix}`,async(req:any)=>{const [old]=await database.db.select().from(patches).where(eq(patches.id,req.params.id));const [row]=await database.db.update(patches).set({status,publishedAt:status==='published'?new Date():old?.publishedAt,updatedAt:new Date()}).where(eq(patches.id,req.params.id)).returning();await audit(`patch.${suffix}`,'patch',req.params.id,old,row,req);return {patch:row};});
  app.get('/v1/admin/config', async () => ({ config: await database.db.select().from(runtimeConfig) }));
  app.patch('/v1/admin/config/:key', async (req: any) => { const [old] = await database.db.select().from(runtimeConfig).where(eq(runtimeConfig.key, req.params.key)); if (!old) throw new ApiError(404, 'CONFIG_NOT_FOUND', 'Config key not found'); const [next] = await database.db.update(runtimeConfig).set({ value: (req.body as any)?.value, updatedBy: 'admin', updatedAt: new Date() }).where(eq(runtimeConfig.key, req.params.key)).returning(); await database.db.insert(auditLogs).values({ actorType: 'admin', actorId: 'bootstrap', action: 'runtime_config.update', entityType: 'runtime_config', entityId: req.params.key, oldValue: old, newValue: next, ipAddress: req.ip }); return { config: next }; });
  app.get('/v1/admin/feature-flags', async () => ({ featureFlags: await database.db.select().from(featureFlags) }));
  app.patch('/v1/admin/feature-flags/:key', async (req: any) => { const [old] = await database.db.select().from(featureFlags).where(eq(featureFlags.key, req.params.key)); const [next] = await database.db.update(featureFlags).set({ enabled: Boolean((req.body as any)?.enabled), updatedBy: 'admin', updatedAt: new Date() }).where(eq(featureFlags.key, req.params.key)).returning(); await database.db.insert(auditLogs).values({ actorType: 'admin', actorId: 'bootstrap', action: 'feature_flag.update', entityType: 'feature_flag', entityId: req.params.key, oldValue: old, newValue: next, ipAddress: req.ip }); return { featureFlag: next }; });
  app.get('/v1/admin/queues', async () => ({ queues: await database.db.select().from(queueEntries).limit(100) }));
  app.get('/v1/admin/matches', async () => ({ matches: await database.db.select().from(matches).orderBy(desc(matches.createdAt)).limit(100) }));
  app.get('/v1/admin/matches/:id',async(req:any)=>matchDto(database,req.params.id,null,false));
  app.post('/v1/admin/matches/:id/start',async(req:any)=>lifecycle.adminStart(req.params.id,req.ip));
  app.post('/v1/admin/matches/:id/complete',async(req:any)=>lifecycle.complete(req.params.id,req.body as Completion,req.ip));
  app.post('/v1/admin/matches/:id/cancel', async (req: any) => lifecycle.adminCancel(req.params.id,String(req.body?.reason??''),req.ip));
  app.get('/v1/admin/audit', async () => ({ audit: await database.db.select().from(auditLogs).orderBy(desc(auditLogs.createdAt)).limit(100) }));
  async function audit(action:string,entityType:string,entityId:string,oldValue:any,newValue:any,req:any){await database.db.insert(auditLogs).values({actorType:'admin',actorId:'bootstrap',action,entityType,entityId,oldValue,newValue,ipAddress:req.ip});}
  app.addHook('onClose', async () => { await database.pool.end(); });
  return app;
}

export async function runMatchmakingCycle(database: Database, env: Env) {
  const lifecycle=new MatchLifecycleService(database.pool);
  await lifecycle.processTimeouts();
  await new BalancePatchService(database.pool).publishDue({error:()=>{/* Failure of one scheduled patch must not stop matchmaking. */}});
  const ready=(await database.pool.query(`select id from matches where status='ready' order by ready_at for update skip locked limit 20`)).rows;
  for(const row of ready){try{await lifecycle.beginConnecting(row.id)}catch{/* One match must not stop the worker cycle. */}}
  await database.pool.query(`delete from steam_auth_states where expires_at<now()-interval '1 day'; delete from sessions where expires_at<now()-interval '30 days' or revoked_at<now()-interval '30 days'`);
  const enabled = await readCfg(database, 'matchmaking_enabled', env.MATCHMAKING_ENABLED);
  if (!enabled) return null;
  const waits = await database.db.select().from(queueEntries).where(eq(queueEntries.status, 'waiting')).orderBy(queueEntries.joinedAt).limit(10);
  if (waits.length < 10 && !env.DEMO_MATCHMAKING_ENABLED) return null;
  const botsNeeded = Math.max(0, 10 - waits.length);
  const bots = botsNeeded ? await database.db.select().from(players).where(eq(players.isBot, true)).limit(botsNeeded) : [];
  if (waits.length + bots.length < 10) return null;
  const seedRegions=waits[0]?.regions??['EU West'];
  const candidates: Candidate[] = [...waits.map((q) => ({ playerId: q.playerId, rating: q.ratingSnapshot, trustScore: q.trustScoreSnapshot, primaryRole: q.primaryRole as any, roles:(q.roles?.length?q.roles:[q.primaryRole]) as any, regions:q.regions, joinedAt: q.joinedAt })), ...bots.map((b, i) => ({ playerId: b.id, rating: b.rating, trustScore: b.trustScore, primaryRole: DOTA_ROLES[i % DOTA_ROLES.length] as any, roles:[...DOTA_ROLES] as any, regions:b.regions.filter(r=>seedRegions.includes(r)), joinedAt: new Date(), isBot: true }))].slice(0, 10);
  const balanced = balanceTeams(candidates, 10); if (!balanced) return null;
  const region=selectMatchRegion(candidates);if(!region)return null;
  return database.db.transaction(async (tx) => { const [balancePatch]=await tx.select({id:balancePatches.id,version:balancePatches.version}).from(balancePatches).where(and(eq(balancePatches.status,'published'),eq(balancePatches.releaseChannel,'production'))).orderBy(desc(balancePatches.publishedAt)).limit(1); const [m] = await tx.insert(matches).values({ roomCode: `TRUST-${randomUUID().slice(0, 8)}`, region, acceptDeadline: new Date(Date.now() + env.MATCH_ACCEPT_TIMEOUT_MS), balancePatchId:balancePatch?.id, balancePatchVersion:balancePatch?.version }).returning(); const rows = [...balanced.radiant.map((c) => ({ c, team: 'radiant' })), ...balanced.dire.map((c) => ({ c, team: 'dire' }))]; await tx.insert(matchPlayers).values(rows.map(({ c, team }) => ({ matchId: m!.id, playerId: c.playerId, team, role: c.primaryRole, ratingBefore: c.rating, trustScoreBefore: c.trustScore, acceptStatus: c.isBot ? 'accepted' : 'pending', acceptedAt: c.isBot ? new Date() : null,connectionStatus:c.isBot?'connected':'pending',connectedAt:c.isBot?new Date():null }))); if (waits.length) await tx.update(queueEntries).set({ status: 'matched', matchedAt: new Date() }).where(inArray(queueEntries.id, waits.map((w) => w.id))); return m; });
}
async function readCfg(database: Database, key: string, fallback: any) { const [r] = await database.db.select().from(runtimeConfig).where(eq(runtimeConfig.key, key)).limit(1); return r?.value ?? fallback; }
export function attachSocket(app: any, server: any, env: Env) { const io = new SocketIOServer(server, { cors: { origin: env.CORS_ORIGINS.split(',').map((s) => s.trim()), credentials: true }, pingInterval: 25000, pingTimeout: 20000 }); io.on('connection', (s) => { s.join('public-config'); s.on('join:player', (id: string) => s.join(`player:${id}`)); s.on('join:match', (id: string) => s.join(`match:${id}`)); }); app.io = io; return io; }
function localize(value:any,locale:string){if(value&&typeof value==='object'&&!Array.isArray(value))return value[locale]??value.en;return value}
function publicPlayer(p: any) { return { id: p.id, steamId64:/^7656119\d{10}$/.test(p.steamId??'')?p.steamId:null, personaName:p.displayName, avatarUrl:p.avatarUrl,profileUrl:p.profileUrl,profileVisibility:p.profileVisibility, status: p.status, rating: p.rating, trustScore: p.trustScore, regions: p.regions,roles:p.preferredRoles?.length?p.preferredRoles:(p.preferredRole?[p.preferredRole]:[]),primaryRole:p.preferredRole,registeredAt:p.createdAt, isBot: p.isBot }; }
declare module 'fastify' { interface FastifyInstance { io?: SocketIOServer | null } }

async function assertParticipant(database:Database,id:string,playerId:string){const row=await database.pool.query('select 1 from match_players where match_id=$1 and player_id=$2',[id,playerId]);if(!row.rowCount)throw new ApiError(403,'NOT_MATCH_PARTICIPANT','Not a match participant')}
async function matchDto(database:Database,id:string,selfId:string|null,hideUnauthorized:boolean){const m=(await database.pool.query('select * from matches where id=$1',[id])).rows[0];if(!m)throw new ApiError(404,'MATCH_NOT_FOUND','Match not found');const roster=(await database.pool.query(`select mp.*,p.display_name,p.avatar_url,p.is_bot from match_players mp join players p on p.id=mp.player_id where mp.match_id=$1 order by mp.team,mp.role,p.id`,[id])).rows;if(hideUnauthorized&&!roster.some(p=>p.player_id===selfId))throw new ApiError(404,'MATCH_NOT_FOUND','Match not found');const map=(p:any)=>({playerId:p.player_id,personaName:p.display_name,avatarUrl:p.avatar_url,team:p.team,primaryRole:p.role,ratingBefore:p.rating_before,ratingAfter:p.rating_after,trustScoreBefore:p.trust_score_before,trustScoreAfter:p.trust_score_after,acceptStatus:p.accept_status,connectionStatus:p.connection_status,isBot:p.is_bot});const accepted=roster.filter(p=>p.accept_status==='accepted').length;return {match:{id:m.id,roomCode:m.room_code,status:m.status,region:m.region,balancePatchId:m.balance_patch_id,balancePatchVersion:m.balance_patch_version,acceptDeadline:m.accept_deadline,readyAt:m.ready_at,connectingAt:m.connecting_at,inProgressAt:m.in_progress_at,completedAt:m.completed_at,cancelledAt:m.cancelled_at,winner:m.winner,radiantScore:m.radiant_score,direScore:m.dire_score,durationSeconds:m.duration_seconds,completionReason:m.completion_reason,cancellationReason:m.cancellation_reason,version:m.version,updatedAt:m.updated_at},self:selfId?map(roster.find(p=>p.player_id===selfId)):null,acceptance:{accepted,required:roster.length},teams:{radiant:roster.filter(p=>p.team==='radiant').map(map),dire:roster.filter(p=>p.team==='dire').map(map)}}}
async function matchHistory(database:Database,playerId:string,query:any){const limit=Math.min(100,Math.max(1,Number(query?.limit)||20));const cursor=query?.cursor?new Date(String(query.cursor)):null;if(cursor&&Number.isNaN(cursor.getTime()))throw new ApiError(400,'INVALID_CURSOR','Cursor must be an ISO timestamp');const values:any[]=[playerId,limit+1];let cursorSql='';if(cursor){values.push(cursor);cursorSql='and m.created_at<$3'}const rows=(await database.pool.query(`select m.id,m.created_at,m.status,m.region,m.room_code,m.balance_patch_id,m.balance_patch_version,m.winner,m.radiant_score,m.dire_score,m.duration_seconds,mp.team,mp.role,mp.rating_before,mp.rating_after,mp.trust_score_before,mp.trust_score_after from match_players mp join matches m on m.id=mp.match_id where mp.player_id=$1 ${cursorSql} order by m.created_at desc limit $2`,values)).rows;const page=rows.slice(0,limit).map(r=>({matchId:r.id,date:r.created_at,status:r.status,region:r.region,balancePatchId:r.balance_patch_id,balancePatchVersion:r.balance_patch_version,team:r.team,primaryRole:r.role,outcome:r.status==='completed'?(r.winner===r.team?'win':'loss'):null,radiantScore:r.radiant_score,direScore:r.dire_score,durationSeconds:r.duration_seconds,ratingBefore:r.rating_before,ratingAfter:r.rating_after,ratingDelta:r.rating_after==null?null:r.rating_after-r.rating_before,trustScoreBefore:r.trust_score_before,trustScoreAfter:r.trust_score_after,trustDelta:r.trust_score_after==null?null:r.trust_score_after-r.trust_score_before,roomCode:r.room_code}));return {matches:page,nextCursor:rows.length>limit?page.at(-1)?.date:null}}
async function adminDashboard(database:Database){const {rows:[r]}=await database.pool.query(`select (select count(*)::int from players) total_players,(select count(*)::int from players where last_seen_at>now()-interval '5 minutes') players_online,(select count(*)::int from queue_entries where status='waiting') players_queued,(select count(*)::int from matches where status='accepting') accepting_matches,(select count(*)::int from matches where status='connecting') connecting_matches,(select count(*)::int from matches where status='in_progress') in_progress_matches,(select count(*)::int from matches where status='completed' and completed_at>=current_date) completed_today,(select count(*)::int from matches where status='cancelled' and cancelled_at>=current_date) cancelled_today,(select coalesce(avg(extract(epoch from(matched_at-joined_at))),0)::float from queue_entries where status='matched') average_queue_seconds,coalesce((select avg((accept_status='accepted')::int)::float from match_players),0) acceptance_rate,coalesce((select avg((accept_status='timed_out')::int)::float from match_players),0) timeout_rate,(select coalesce(jsonb_object_agg(region,n),'{}') from(select region,count(*)::int n from matches where status='completed' group by region)x) matches_by_region,(select count(*)::int from matches where status='completed' and completed_at>now()-interval '24 hours') matches_last24_hours,(select count(*)::int from rating_events where created_at>=current_date) rating_events_today,(select count(*)::int from trust_events where created_at>=current_date) trust_events_today`);return camel(r)}
async function adminStats(database:Database,range:string){const intervals:{[k:string]:string}={'24h':'24 hours','7d':'7 days','30d':'30 days'};const interval=intervals[range];if(!interval)throw new ApiError(400,'INVALID_RANGE','range must be 24h, 7d, or 30d');const [series,regions,reasons]=await Promise.all([database.pool.query(`select date_trunc('hour',created_at) bucket,count(*) filter(where status='completed')::int completed,count(*) filter(where status='cancelled')::int cancelled from matches where created_at>now()-$1::interval group by 1 order by 1`,[interval]),database.pool.query(`select region,count(*)::int count from matches where created_at>now()-$1::interval group by region`,[interval]),database.pool.query(`select coalesce(cancellation_reason,'unspecified') reason,count(*)::int count from matches where status='cancelled' and created_at>now()-$1::interval group by 1`,[interval])]);const summary=(await database.pool.query(`select coalesce(avg(extract(epoch from(matched_at-joined_at))) filter(where status='matched'),0)::float average_queue_seconds from queue_entries where joined_at>now()-$1::interval`,[interval])).rows[0];const acceptance=(await database.pool.query(`select coalesce(avg((accept_status='accepted')::int),0)::float acceptance_rate from match_players mp join matches m on m.id=mp.match_id where m.created_at>now()-$1::interval`,[interval])).rows[0];return {range,timeSeries:series.rows,completedMatches:series.rows.reduce((n,r)=>n+r.completed,0),cancelledMatches:series.rows.reduce((n,r)=>n+r.cancelled,0),...camel(summary),...camel(acceptance),regions:regions.rows,cancellationReasons:reasons.rows}}
function camel(row:any){return Object.fromEntries(Object.entries(row??{}).map(([k,v])=>[k.replace(/_([a-z])/g,(_,c)=>c.toUpperCase()),v]))}
